const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";const META={title:"CS 18-19 Public Policy and Citizen Input Intro",assignmentKey:"gov-cs18-19-intro-2026-v1"};
const URL={"state":"https://www.state.gov/about/","cbo":"https://www.cbo.gov/about/overview","lsc":"https://www.lsc.ohio.gov/","courts":"https://www.supremecourt.ohio.gov/courts/judicial-system/ohio-trial-courts/","input":"https://www.usa.gov/elected-officials"};const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,"CS 18-19","What is a public-policy issue?","Define it as a public problem government may address through action or rules.",[["public","community"],["problem","issue"],["government"],["action","policy","rule"]],URL.input,2),
A('q2',2,"CS 18-19","Why should policymakers study consequences before acting?","Consider intended and unintended effects on people, cost, and effectiveness.",[["effect","result","consequence"],["people","cost","effective"]],URL.cbo,2),
A('q3',3,"CS 18-19","What public-policy role does the U.S. Department of State perform?","On About, look for foreign policy, diplomacy, and relationships with other nations.",[["foreign policy","diplomacy"],["nation","country","international"]],URL.state,2),
A('q4',4,"CS 18-19","What does an embassy do?","Connect an embassy to official U.S. representation and diplomacy in another nation.",[["represent"],["united states","u.s.","american"],["country","nation"],["diplomacy","foreign"]],URL.state,2),
A('q5',5,"CS 18-19","What does the Congressional Budget Office provide to Congress?","Look for nonpartisan budget and economic analysis.",[["nonpartisan"],["budget"],["economic","economy"],["analysis","estimate"]],URL.cbo,2),
A('q6',6,"CS 18-19","Why is CBO part of the legislative branch rather than executive branch?","CBO supports Congress with information for legislative and budget decisions.",[["congress","legislative"],["information","analysis"],["budget","law","decision"]],URL.cbo,2),
A('q7',7,"CS 18-19","What does the Ohio Legislative Service Commission do?","Look for research and drafting bills for Ohio legislators.",[["research","analysis"],["draft","write"],["bill","legislation"],["legislator"]],URL.lsc,2),
A('q8',8,"CS 18-19","How can an Ohio Court of Common Pleas affect policy implementation?","Connect trial courts to applying law and using sentencing rules in cases.",[["apply","interpret"],["law"],["sentence","case","trial"]],URL.courts,2),
A('q9',9,"CS 18-19","What is one policy action a county commission may take?","Use the state example: offering a tax abatement to encourage development.",[["county"],["tax abatement","tax break"],["develop","business"]],URL.input,2),
A('q10',10,"CS 18-19","Why might government levels collaborate on one policy issue?","Explain that complex problems cross boundaries and require shared authority or resources.",[["level","federal","state","local"],["resource","authority","boundary"],["work together","cooperat","collaborat"]],URL.input,2),
A('q11',11,"CS 18-19","How can branches conflict over public policy?","Describe disagreement about authority, funding, interpretation, or implementation.",[["disagree","conflict"],["authority","fund","interpret","implement"]],URL.input,2),
A('q12',12,"CS 18-19","How can a citizen influence an executive agency rule?","Provide information or submit public comments during the rulemaking process.",[["comment","information"],["agency","executive"],["rule"]],URL.input,2),
A('q13',13,"CS 18-19","How can a citizen influence the legislative branch?","Choose lobbying, testimony, proposing a law, letters, or contacting lawmakers.",[["lobby","testimony","propose","letter","contact"],["legislator","congress","law"]],URL.input,2),
A('q14',14,"CS 18-19","How can a person try to influence a court decision?","Describe submitting a legal brief or supporting an appropriate court case.",[["brief","legal argument","case"],["court","judicial"]],URL.courts,2),
A('q15',15,"CS 18-19","Why must citizen action target the correct government entity?","The entity needs jurisdiction and authority to act on that issue.",[["jurisdiction","authority","power"],["issue","problem"],["correct","appropriate"]],URL.input,2),
A('q16',16,"CS 18-19","Choose a method to influence one policy issue and defend your choice.","Name the issue, target, method, and why that method fits the decision-maker.",[["issue"],["agency","branch","official","government"],["comment","lobby","testimony","brief","campaign","demonstration","letter"],["because","fit","authority"]],URL.input,2)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
