(function(){
const T="https://www.archives.gov/founding-docs/bill-of-rights-transcript";
const O="https://www.archives.gov/founding-docs/bill-of-rights/what-does-it-say";
window.BLOCK_CONFIG={
  assignmentKey:"gov-cs8-review-mc-2026-v2",
  title:"CS 8 Comprehensive Review — Bill of Rights",
  description:"Content Statement 8 • Apply civil liberties and limits on federal power to constitutional scenarios.",
  practice:"Analyze scenarios, compare protections, and use primary-source language from the Bill of Rights."
};

// Correct answer is stored first in each raw item, then moved to a balanced A–D position.
const raw=[
["r01","Foundations","Why did demands for a Bill of Rights become important during ratification?",["Many people wanted explicit protections for individual liberty against federal power","Delegates wanted Congress to replace every state constitution with one national legal code","Supporters wanted the president to control elections without review by courts or legislatures","States sought permission to ignore every power listed in the original Constitution"],O,"Read the overview explaining why the first ten amendments were proposed.","The Bill of Rights answered fears that the new federal government could threaten individual liberty."],
["r02","Foundations","Which claim best explains how the Bill of Rights limits government?",["It identifies freedoms and legal protections government must respect","It allows federal officials to suspend any right whenever opposition becomes inconvenient","It transfers all decisions about individual liberty from courts to the executive branch","It guarantees that private citizens can never interfere with one another's choices"],O,"Focus on the overview's description of rights guaranteed to individuals.","The Bill of Rights restrains government by identifying liberties and procedures it must respect."],
["r03","First Amendment","A city requires a permit for a peaceful march but denies it only because officials dislike the marchers' political message. Which protection is most directly threatened?",["Freedom of speech and peaceful assembly","The right to keep and bear arms during public demonstrations","Protection against being tried twice for the same criminal offense","The reservation of undelegated governmental powers to the states"],T,"Read Amendment I for protections involving expression and peaceful gatherings.","Viewpoint-based denial of a peaceful political march implicates speech and assembly."],
["r04","First Amendment","Congress creates an official national church and funds it through a mandatory religious tax. Which First Amendment principle is most directly involved?",["Government may not establish an official religion","Government must provide a criminal jury before collecting any form of public revenue","Citizens may refuse every law that conflicts with an individual political belief","Religious organizations possess all powers not delegated to the federal government"],T,"Read the opening religion clause of Amendment I.","The Establishment Clause prevents Congress from establishing an official religion."],
["r05","First Amendment","A law punishes people solely for attending a peaceful worship service. Which protection provides the strongest challenge?",["Free exercise of religion","Freedom of the press to publish reports about religious organizations","The right of criminal defendants to confront witnesses testifying against them","Protection against government taking private property without just compensation"],T,"In Amendment I, find the protection for religious practice.","Punishing peaceful worship directly burdens the free exercise of religion."],
["r06","First Amendment","A newspaper publishes evidence that a federal agency wasted money, and officials try to stop publication because it is embarrassing. Which liberty is most directly at issue?",["Freedom of the press","The accused person's right to compulsory process for obtaining defense witnesses","The protection against excessive bail before a criminal trial begins","The reserved authority of states to administer their own local governments"],T,"Read Amendment I and locate the protection involving the press.","Freedom of the press protects publication of information and criticism about government."],
["r07","First Amendment","Residents sign a letter asking Congress to repeal an unpopular law. Their action is the clearest example of—",["petitioning the government for redress of grievances","exercising the right to avoid every search supported by a valid warrant","using the guarantee against a second prosecution after a completed trial","claiming an exclusive state power over all forms of public communication"],T,"Read the final protected activity listed in Amendment I.","A request that government change a policy is an exercise of the right to petition."],
["r08","First Amendment","Which government action would most clearly violate freedom of speech?",["Jailing a peaceful speaker because the speaker criticized federal policy","Enforcing a neutral traffic rule that applies equally near every public gathering","Requiring a criminal court to inform an accused person of the formal charges","Obtaining a specific search warrant after presenting evidence of probable cause"],T,"Use Amendment I to identify punishment based on peaceful political expression.","Government ordinarily cannot jail a person simply for peaceful criticism of public policy."],
["r09","Second Amendment","Which situation most directly requires analysis under the Second Amendment?",["A federal law broadly restricts an individual's ability to keep and bear arms","A city searches a resident's locked home without probable cause or a warrant","A court prevents a defendant from calling a witness who supports the defense","Congress taxes citizens to support an officially established national religion"],T,"Read Amendment II and identify the right named in its final clause.","A restriction on keeping and bearing arms directly raises a Second Amendment question."],
["r10","Fourth Amendment","Officers obtain a warrant saying only that they may search 'anywhere in the neighborhood for anything suspicious.' What is the strongest constitutional objection?",["The warrant fails to describe particularly the place and items involved","The warrant violates the rule against being prosecuted twice after an acquittal","The warrant prevents the accused from receiving notice of a criminal accusation","The warrant assigns a power to the federal government that belongs only to states"],T,"Read the final words of Amendment IV about what a warrant must describe.","The Fourth Amendment requires particularity rather than a limitless general warrant."],
["r11","Fourth Amendment","Police want a judge to issue a search warrant. Which showing does the Fourth Amendment normally require?",["Probable cause supported by oath or affirmation","A general feeling that evidence may appear somewhere during an unrestricted search","A promise that any seized evidence will automatically produce a criminal conviction","Approval from a jury selected before the search or the filing of formal charges"],T,"Find the requirements immediately following 'no Warrants shall issue.'","The text requires probable cause supported by oath or affirmation."],
["r12","Fourth Amendment","Without a warrant or emergency, officers force entry into a home merely to see whether they can discover evidence. Which right is most directly implicated?",["Security against unreasonable searches and seizures","Protection against excessive fines imposed after a lawful conviction","The right to have favorable witnesses brought into a criminal trial","Freedom to ask Congress for a change in national public policy"],T,"Read the opening protection in Amendment IV and note the reference to houses.","An unsupported exploratory home search raises the core Fourth Amendment concern."],
["r13","Fourth Amendment","Which fact would best support a warrant that satisfies the Fourth Amendment?",["Specific sworn facts connect evidence of a crime to a named location","An officer requests authority to search every residence in a city without identifying evidence","A government official dislikes the homeowner's lawful criticism of a federal program","A prosecutor guarantees that the person searched will later waive the right to counsel"],T,"Identify probable cause, oath or affirmation, and particular description in Amendment IV.","Specific sworn facts linking evidence to a particular place support probable cause and particularity."],
["r14","Fourth Amendment","Why did the Fourth Amendment reject general warrants?",["They permit broad searches without specific justification or defined limits","They guarantee defendants more than one jury trial for exactly the same offense","They require the government to pay compensation whenever it regulates private conduct","They allow state governments to exercise only powers specifically delegated by Congress"],T,"Compare the protection against unreasonable searches with the warrant requirements.","Specific warrants limit official discretion and reduce unjustified intrusions."],
["r15","Fifth Amendment","After a jury acquits a defendant, the government immediately prosecutes the person again for the same offense simply because prosecutors dislike the verdict. Which protection applies?",["The protection against double jeopardy","The freedom to assemble peacefully and petition the national government","The guarantee that warrants particularly describe the items officers may seize","The reservation of powers not delegated to the United States"],T,"Find the words 'same offence' and 'twice put in jeopardy' in Amendment V.","Double jeopardy generally bars a second prosecution for the same offense after acquittal."],
["r16","Fifth Amendment","Investigators threaten a suspect with punishment unless the suspect gives testimony admitting personal guilt. Which protection is most directly involved?",["The privilege against compelled self-incrimination","The right of the public and press to attend every governmental meeting without exception","The prohibition against excessive monetary fines following a lawful conviction","The power of a state to regulate a subject not delegated to the national government"],T,"Read the clause about being compelled to be a witness against oneself.","The Fifth Amendment protects a person from being forced to give self-incriminating testimony."],
["r17","Fifth Amendment","Government takes private land for a public highway but refuses to pay the owner. Which Fifth Amendment protection is most relevant?",["Private property taken for public use requires just compensation","Every criminal prosecution requires a second jury to review the first jury's verdict","Government must permit any religious practice regardless of its effect on other people","A search warrant may authorize any location if an officer signs the application"],T,"Read the final clause of Amendment V concerning private property.","The Takings Clause requires just compensation when private property is taken for public use."],
["r18","Fifth Amendment","A government agency removes a person's liberty without notice or a fair opportunity to respond. Which constitutional principle is most directly violated?",["Due process of law","The right to keep and bear arms as part of a well-regulated militia","The right to publish criticism without prior approval from a government official","The protection against a court imposing excessive bail before trial"],T,"Find 'life, liberty, or property' and the rule that precedes deprivation.","Due process requires fair legal procedures before government deprives a person of liberty."],
["r19","Fifth Amendment","Which sequence best demonstrates due process?",["Government gives notice, uses fair procedures, and allows a meaningful response","Government imposes punishment first and reveals the accusation only after every appeal ends","An officer conducts an unlimited search and asks a judge to approve it afterward","Congress selects an official religion and permits citizens to petition against it later"],T,"Read Amendment V and connect due process with life, liberty, and property.","Notice, fair procedures, and an opportunity to respond are central features of due process."],
["r20","Sixth Amendment","A defendant learns the exact criminal charge only after the trial has ended. Which Sixth Amendment guarantee was denied?",["The right to be informed of the nature and cause of the accusation","The right to prevent government from taking property for public use with compensation","The right to avoid every search even when supported by a particular warrant","The right of states to exercise powers prohibited to them by the Constitution"],T,"Find the clause requiring an accused person to be informed of the accusation.","Notice of the charge allows the accused to understand the case and prepare a defense."],
["r21","Sixth Amendment","A criminal case is delayed for many years solely because the government refuses to schedule it. Which guarantee is most directly threatened?",["The right to a speedy trial","The right to petition Congress for correction of a public grievance","The right against a second prosecution after acquittal for the same offense","The right to receive just compensation when private land is taken for public use"],T,"Read the first trial guarantee in Amendment VI.","The Sixth Amendment protects an accused person from unjustified delay through the speedy-trial guarantee."],
["r22","Sixth Amendment","The prosecution relies on a witness but the court forbids the defendant from questioning that witness. Which right is most directly denied?",["The right to confront adverse witnesses","The protection against an excessive fine imposed as punishment after conviction","The freedom of a newspaper to report criticism of elected public officials","The reservation of undelegated governmental authority to states or the people"],T,"Find the clause about being confronted with witnesses against the accused.","Confrontation allows the defense to challenge testimony offered against the accused."],
["r23","Sixth Amendment","A court refuses to allow a defendant to call an available witness whose testimony supports the defense. Which guarantee applies?",["Compulsory process for obtaining defense witnesses","The prohibition against Congress establishing an official national religion","The requirement that search warrants describe the places and things involved","The protection against another prosecution for the same offense after jeopardy"],T,"Read Amendment VI for the clause about obtaining witnesses in one's favor.","Compulsory process helps an accused person bring favorable witnesses to court."],
["r24","Sixth Amendment","An accused person cannot understand the charges or prepare a defense and is denied legal assistance. Which protection is most directly implicated?",["The right to assistance of counsel","The right of states to exercise every power held by the national government","The freedom to avoid all regulations affecting ownership or use of weapons","The protection against government compensation for property used by the public"],T,"Read the final phrase of Amendment VI.","Counsel provides legal assistance needed to understand the case and present a defense."],
["r25","Sixth Amendment","Why does the Sixth Amendment require an impartial jury?",["To have the evidence judged by decision-makers without improper bias","To ensure that government may retry a defendant until a jury returns the preferred verdict","To allow jurors to conduct broad searches for additional evidence outside the courtroom","To transfer control of every criminal prosecution from state courts to Congress"],T,"Find the jury requirement near the beginning of Amendment VI.","An impartial jury supports a fair judgment based on evidence rather than improper bias."],
["r26","Eighth Amendment","A judge sets an extraordinarily high bail amount only to punish an unconvicted defendant. Which provision is most directly involved?",["The prohibition against excessive bail","The privilege against compelled testimony admitting personal criminal responsibility","The protection of peaceful political speech criticizing federal government policy","The requirement that a warrant name the specific location officers may search"],T,"Read the first prohibition in Amendment VIII.","The Eighth Amendment prohibits excessive bail, including bail used improperly as punishment."],
["r27","Eighth Amendment","A court imposes a massive fine grossly disproportionate to a minor offense. Which protection should be analyzed?",["The prohibition against excessive fines","The accused person's right to confront witnesses and obtain favorable testimony","The people's right to assemble peacefully and petition the government for change","The reservation of powers to states when those powers are not nationally delegated"],T,"Read the middle prohibition in Amendment VIII.","The Excessive Fines Clause limits grossly disproportionate financial penalties."],
["r28","Eighth Amendment","Which situation most directly raises the ban on cruel and unusual punishment?",["Officials deliberately impose a barbaric punishment after conviction","A newspaper reports accurate information that makes a public official look irresponsible","A judge issues a focused warrant based on sworn evidence of probable cause","A defendant asks the court to subpoena a witness who can support the defense"],T,"Read the final protection listed in Amendment VIII.","The Eighth Amendment bars cruel and unusual punishments."],
["r29","Ninth Amendment","Why is the Ninth Amendment important when interpreting the listed rights?",["Listing some rights does not mean the people possess no other rights","Every power not listed in the Constitution automatically belongs only to Congress","Rights named in the Constitution may be ignored whenever a majority votes to do so","State governments may establish official religions because Amendment I mentions Congress"],T,"Read Amendment IX and focus on the effect of enumerating certain rights.","The Ninth Amendment warns that listing certain rights must not deny other rights retained by the people."],
["r30","Tenth Amendment","Congress claims a power that the Constitution neither delegates to the United States nor prohibits to the states. According to the Tenth Amendment, where is that power reserved?",["To the states respectively, or to the people","To the president alone whenever Congress has not enacted a national policy","To federal courts so judges may create an unlimited national police power","To Congress because every unlisted governmental power becomes federal by default"],T,"Read Amendment X and identify who retains undelegated powers.","The Tenth Amendment reserves undelegated powers to the states or the people."],
["r31","Tenth Amendment","Which statement best connects the Tenth Amendment to federalism?",["It reinforces a division of authority between national and state governments","It requires all state laws to receive advance approval from both houses of Congress","It gives the national government every power not expressly prohibited by the Constitution","It prevents the people from retaining any governmental authority outside elected offices"],T,"Connect reserved powers in Amendment X with divided governmental authority.","Reserved powers reinforce federalism by preserving a sphere of state or popular authority."],
["r32","Synthesis","Which comparison between the Fourth and Sixth Amendments is most accurate?",["The Fourth limits searches and warrants; the Sixth protects fairness in criminal trials","The Fourth protects religious exercise; the Sixth reserves undelegated powers to the states","The Fourth prohibits excessive punishment; the Sixth protects publication by the press","The Fourth prevents double jeopardy; the Sixth requires compensation for property takings"],T,"Compare the text of Amendments IV and VI.","The Fourth regulates searches and warrants, while the Sixth specifies rights of the criminally accused at trial."]
];

function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function positions(){let p=[0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3];do{p=shuffle(p)}while(p.some((v,i)=>i>1&&p[i-1]===v&&p[i-2]===v));return p}
// A concise but plausible distractor on every item prevents “pick the shortest” from becoming a pattern.
const concise={
r01:"To expand federal taxing power",r02:"It creates state governments",r03:"Freedom of the press",r04:"Free exercise of religion",
r05:"Freedom of assembly",r06:"Right to petition",r07:"exercising freedom of the press",r08:"Requiring a protest permit",
r09:"A ban on public petitions",r10:"It lacks a grand jury",r11:"An impartial jury verdict",r12:"Freedom of political speech",
r13:"A prosecutor's written request",r14:"They delay criminal trials",r15:"The right to counsel",r16:"The right to a public trial",
r17:"Protection from double jeopardy",r18:"Equal protection",r19:"Immediate punishment",r20:"The right to confront witnesses",
r21:"The right to counsel",r22:"The right to a public trial",r23:"An impartial jury",r24:"A speedy public trial",
r25:"To protect freedom of speech",r26:"The right to petition",r27:"Protection from double jeopardy",r28:"An excessive monetary fine",
r29:"Congress has unlimited power",r30:"To Congress alone",r31:"It creates one national authority",r32:"Both regulate religious liberty"
};
const ordered=shuffle(raw),pos=positions();
window.BLOCK_QUESTIONS=ordered.map((r,n)=>{
  const correct=r[3][0],wrong=r[3].slice(1);wrong[0]=concise[r[0]];const randomizedWrong=shuffle(wrong),answer=pos[n],choices=randomizedWrong.slice();
  choices.splice(answer,0,correct);
  return{id:r[0],cs:"CS 8",topic:r[1],prompt:r[2],choices,answer,source:r[4],where:r[5],explanation:r[6],hint:`Use the source link and the “Where to look” direction. ${r[5]}`};
});
})();
