(function(){
const T="https://www.archives.gov/founding-docs/bill-of-rights-transcript";
const O="https://www.archives.gov/founding-docs/bill-of-rights/what-does-it-say";
window.BLOCK_CONFIG={assignmentKey:"gov-cs8-intro-mc-2026-v2",title:"CS 8 Intro — Bill of Rights",description:"Content Statement 8 • Civil liberties and limits on federal power.",practice:"Use the linked primary source to identify and apply protections in the Bill of Rights."};
const raw=[
["q01","Foundations","What is the Bill of Rights?",["The first ten amendments to the Constitution","The seven original articles of the Constitution","The opening paragraph of the Declaration","The collection of all Supreme Court opinions"],0,O,"Read the opening paragraph. Identify how many amendments make up the Bill of Rights.","The Bill of Rights is the first ten amendments to the Constitution."],
["q02","Foundations","Why was the Bill of Rights added to the Constitution?",["To protect individual liberties and limit federal power","To replace the Constitution with state laws","To establish the executive branch and presidency","To give Congress unlimited authority over citizens"],0,O,"Read the overview and focus on rights in relation to government.","The amendments reassured opponents of ratification by protecting liberties and limiting federal power."],
["q03","Foundations","Which description best defines civil liberties?",["Freedoms protected from improper government interference","Benefits provided only to elected federal officials","Powers reserved exclusively for state legislatures","Duties citizens must perform before receiving rights"],0,O,"Find the sentence describing rights and liberties guaranteed to individuals.","Civil liberties are protected freedoms that government ordinarily may not violate."],
["q04","First Amendment","Which list contains all five First Amendment freedoms?",["Religion, speech, press, assembly, and petition","Speech, privacy, jury trial, voting, and property","Religion, weapons, counsel, bail, and federalism","Press, warrants, due process, states, and equality"],0,T,"Read Amendment I and identify each freedom protected from congressional interference.","The First Amendment protects religion, speech, press, peaceful assembly, and petition."],
["q05","First Amendment","A newspaper criticizes a federal policy. Which freedom most directly protects that action?",["Freedom of the press","Freedom of assembly","Right to bear arms","Right to legal counsel"],0,T,"In Amendment I, locate the phrase concerning the press.","Freedom of the press protects publication of criticism and information."],
["q06","First Amendment","Citizens gather peacefully outside city hall. Which freedom are they exercising?",["Freedom of assembly","Freedom of the press","Protection from self-incrimination","Protection from unreasonable searches"],0,T,"Find the words “peaceably to assemble” in Amendment I.","Peaceful public gatherings are protected by freedom of assembly."],
["q07","First Amendment","Citizens ask Congress to change a law. Which freedom are they exercising?",["Right to petition","Freedom of the press","Right to counsel","Right to bear arms"],0,T,"Read the final protection listed in Amendment I.","Petition protects the right to ask government to address a grievance or change policy."],
["q08","First Amendment","Which action is protected by the Free Exercise Clause?",["Practicing a religion without improper government interference","Requiring every citizen to join an official national church","Allowing Congress to choose one faith for the entire country","Punishing peaceful worship solely because officials dislike it"],0,T,"In Amendment I, compare establishment of religion with free exercise.","The Free Exercise Clause protects religious practice from improper government restriction."],
["q09","Second Amendment","What right is protected by the Second Amendment?",["The right to keep and bear arms","The right to refuse every tax","The right to vote in federal elections","The right to receive a government attorney"],0,T,"Read Amendment II and locate the phrase “keep and bear Arms.”","The Second Amendment protects the right of the people to keep and bear arms."],
["q10","Fourth Amendment","The Fourth Amendment protects people against—",["unreasonable searches and seizures","being tried twice for the same offense","cruel and unusual punishments","being denied a speedy public trial"],0,T,"Read the opening words of Amendment IV.","The Fourth Amendment protects persons, homes, papers, and property from unreasonable searches and seizures."],
["q11","Fourth Amendment","What must normally support the issuance of a search warrant?",["Probable cause supported by oath or affirmation","A general suspicion without supporting facts","Permission from any private citizen nearby","A request from the officer conducting the search"],0,T,"In Amendment IV, read the words immediately following “no Warrants shall issue.”","A warrant ordinarily requires probable cause supported by oath or affirmation."],
["q12","Fourth Amendment","What must a valid warrant particularly describe?",["The place to search and the persons or things to seize","Every location the police might possibly investigate","Only the name of the officer requesting the warrant","The criminal sentence that must follow the search"],0,T,"Finish Amendment IV and identify both things a warrant must describe.","A warrant must particularly describe the place and the persons or things involved."],
["q13","Fourth Amendment","Police search a home without a warrant, emergency, or probable cause. Which protection is most directly involved?",["Protection from unreasonable searches and seizures","Protection from excessive bail and fines","Protection against compelled testimony","Protection of peaceful religious exercise"],0,T,"Match a home search with the protection stated in Amendment IV.","An unjustified home search directly raises Fourth Amendment concerns."],
["q14","Fifth Amendment","What does protection against self-incrimination mean?",["Government cannot force a person to testify against oneself","A defendant may never be questioned by any court","A witness may ignore every lawful court order","Government must dismiss every charge after an arrest"],0,T,"In Amendment V, find the clause about being a witness against oneself.","The Fifth Amendment prevents compelled testimony that would incriminate the speaker."],
["q15","Fifth Amendment","What is double jeopardy?",["Being prosecuted twice for the same offense after jeopardy has attached","Receiving two different charges arising from separate criminal acts","Facing both a fine and imprisonment after a lawful conviction","Appealing a conviction to a higher court for legal review"],0,T,"Find “same offence” and “twice put in jeopardy” in Amendment V.","Double jeopardy generally prevents a second prosecution for the same offense after jeopardy attaches."],
["q16","Fifth Amendment","Which statement best explains due process?",["Government must follow fair legal procedures before depriving a person of life, liberty, or property","Government may punish a person without notice whenever officials believe punishment is useful","Courts must automatically acquit every defendant who challenges a government action","Only state governments must obey established laws and courtroom procedures"],0,T,"Find “life, liberty, or property” and “due process of law” in Amendment V.","Due process requires government to use fair, established legal procedures."],
["q17","Fifth Amendment","A defendant refuses to answer a question that would admit guilt. Which protection applies?",["Protection against self-incrimination","Protection against excessive bail","Right to peaceful assembly","Reservation of powers to the states"],0,T,"Connect forced testimony against oneself with Amendment V.","The self-incrimination clause protects a defendant from being compelled to admit guilt."],
["q18","Sixth Amendment","Which set contains three rights guaranteed to a criminal defendant by the Sixth Amendment?",["Speedy public trial, impartial jury, and assistance of counsel","Freedom of religion, freedom of speech, and freedom of the press","Protection from searches, probable cause, and a specific warrant","Protection from excessive bail, excessive fines, and cruel punishment"],0,T,"Read Amendment VI and identify protections governing a criminal trial.","The Sixth Amendment includes a speedy public trial, impartial jury, notice, witnesses, and counsel."],
["q19","Sixth Amendment","What does the Sixth Amendment right to counsel provide?",["Assistance of an attorney in preparing and presenting a defense","Automatic dismissal of charges when a defendant requests it","A guarantee that every criminal trial will end in acquittal","Permission for defendants to select the judge hearing the case"],0,T,"Read the final phrase of Amendment VI concerning assistance of counsel.","The right to counsel provides legal assistance for the accused person's defense."],
["q20","Sixth Amendment","Why must an accused person be informed of the nature and cause of the accusation?",["So the accused can understand the charge and prepare a defense","So the government can avoid presenting evidence at trial","So the jury can decide the case before hearing witnesses","So punishment can begin before the defendant enters a plea"],0,T,"Find the clause requiring notice of the accusation in Amendment VI.","Knowing the charges is necessary for an accused person to prepare a meaningful defense."],
["q21","Sixth Amendment","A criminal trial is delayed for years without a valid reason. Which right may have been violated?",["The right to a speedy trial","The right to petition government","The right to bear arms","The right against double jeopardy"],0,T,"Read the first trial protection listed in Amendment VI.","The Sixth Amendment guarantees an accused person a speedy and public trial."],
["q22","Eighth Amendment","Which punishments does the Eighth Amendment forbid?",["Cruel and unusual punishments","All imprisonment following conviction","Every fine imposed by a court","Any punishment authorized by law"],0,T,"Read the final phrase of Amendment VIII.","The Eighth Amendment forbids cruel and unusual punishments."],
["q23","Eighth Amendment","Government imposes an extreme punishment grossly out of proportion to a minor offense. Which amendment is most directly involved?",["The Eighth Amendment","The First Amendment","The Second Amendment","The Tenth Amendment"],0,T,"Match an extreme punishment with the final protection in Amendment VIII.","A grossly disproportionate punishment raises an Eighth Amendment concern."],
["q24","Tenth Amendment","What happens to a power neither delegated to the United States nor prohibited to the states?",["It is reserved to the states or to the people","It automatically belongs to the president","It must be exercised by the Supreme Court","It disappears and cannot be used by anyone"],0,T,"Read Amendment X after the words “are reserved.”","The Tenth Amendment reserves undelegated powers to the states or the people."],
["q25","Tenth Amendment","How does the Tenth Amendment support federalism?",["It recognizes that governmental power is divided between the nation and the states","It transfers every state responsibility to the national government","It permits state laws to override every part of the Constitution","It prevents the people from retaining any governmental authority"],0,T,"Connect reserved state powers with the division of authority in a federal system.","The Tenth Amendment reinforces federalism by reserving undelegated powers to states or the people."]
];
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function positions(){let p=[0,0,0,0,0,0,0,1,1,1,1,1,1,2,2,2,2,2,2,3,3,3,3,3,3];do{p=shuffle(p)}while(p.some((v,i)=>i>1&&p[i-1]===v&&p[i-2]===v));return p}
const ordered=shuffle(raw),pos=positions();
const built=ordered.map((r,n)=>{const correct=r[3][r[4]],wrong=r[3].filter((_,i)=>i!==r[4]),answer=pos[n],choices=shuffle(wrong);choices.splice(answer,0,correct);return{id:r[0],cs:"CS 8",topic:r[1],prompt:r[2],choices,answer,source:r[5],where:r[6],explanation:r[7],hint:`Use the source link and the “Where to look” direction. ${r[6]}`}});
const alternates={
q02:"To establish the presidency while removing constitutional limits on the authority of the federal government",
q03:"Benefits granted only to federal officeholders after they complete the duties required by the Constitution",
q12:"Every building an officer might choose to enter and every object that might possibly contain evidence",
q13:"Protection from excessive fines and punishments imposed after a lawful criminal conviction in federal court",
q14:"A witness may disregard every lawful question and court order during any civil or criminal proceeding",
q15:"Receiving separate prosecutions for two different offenses committed during two unrelated criminal events",
q16:"Government may remove life, liberty, or property immediately whenever an official believes punishment is useful",
q17:"Protection from unreasonable searches of a home conducted without a valid warrant, emergency, or probable cause",
q19:"Permission for an accused person to choose the judge, jury members, and final sentence before the trial begins",
q20:"So the government may begin imposing punishment before presenting evidence or allowing the accused to respond",
q24:"It automatically becomes an exclusive presidential power that neither the states nor the people may exercise",
q25:"It transfers all governmental responsibilities from the states and the people to the national government"
};
built.forEach(q=>{if(!alternates[q.id])return;const i=q.choices.findIndex((_,n)=>n!==q.answer);q.choices[i]=alternates[q.id]});
window.BLOCK_QUESTIONS=built;
})();
