const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
const META={title:'CS 12–13 Branches Law and Public Policy Intro',assignmentKey:'gov-cs12-13-intro-2026-v1'};
const URL={branches:'https://www.usa.gov/branches-of-government',process:'https://www.house.gov/the-house-explained/the-legislative-process',courts:'https://www.uscourts.gov/about-federal-courts/court-role-and-structure',checks:'https://constitution.congress.gov/browse/essay/intro.6-2-2/ALDE_00000031/',groups:'https://openstax.org/books/american-government-3e/pages/10-1-interest-groups-defined'};
const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,'CS 12 • Law and Public Policy','What is a law?','Use the legislative-process introduction. Explain that a law is a binding rule recognized and enforced by government.',[['rule'],['government'],['enforce','binding','must follow']],URL.process),
A('q2',2,'CS 12 • Law and Public Policy','What is public policy?','Think beyond one law. Describe government actions and procedures used to carry out its functions or address an issue.',[['government'],['action','procedure','program','decision'],['issue','function','goal','problem']],URL.process),
A('q3',3,'CS 12 • Legislative Branch','Name three CS 12 responsibilities of the legislative branch.','On the branches page, open Legislative. Use the Ohio list: makes laws, declares war, and imposes taxes.',[['make','pass','law'],['declare','war'],['tax']],URL.branches,3),
A('q4',4,'CS 12 • Legislative Branch','How does a bill become a federal law?','Use the House legislative-process page. Give the basic path: introduced, considered/passed by both chambers, then sent to the president.',[['bill'],['house','senate','congress','both chambers'],['president','sign']],URL.process,2),
A('q5',5,'CS 12 • Executive Branch','Name three CS 12 responsibilities of the executive branch.','Open Executive. Use the Ohio list: enforces laws, issues executive orders, and appoints or receives ambassadors.',[['enforce','carry out'],['executive order'],['ambassador']],URL.branches,3),
A('q6',6,'CS 12 • Executive Branch','What is an executive order?','On the Executive section, look for presidential directives. Explain that it directs operations of the executive branch.',[['president','executive'],['order','directive'],['agency','branch','operation','carry out']],URL.branches,2),
A('q7',7,'CS 12 • Judicial Branch','Name three CS 12 responsibilities of the judicial branch.','Open Judicial. Use the Ohio list: interprets law, hears original-jurisdiction cases, and hears appeals.',[['interpret'],['original','first'],['appeal','lower court']],URL.branches,3),
A('q8',8,'CS 12 • Judicial Branch','What is original jurisdiction?','Use the court structure page. Original jurisdiction means the court hears the case first.',[['hear','court'],['first','begin','original']],URL.courts),
A('q9',9,'CS 12 • Judicial Branch','What is appellate jurisdiction?','Look for courts reviewing lower-court decisions. An appeal asks a higher court to review.',[['review','appeal'],['lower','decision','court']],URL.courts),
A('q10',10,'CS 12 • Comparison','Compare the main roles of all three branches in one sentence.','Use the three headings: legislative makes law, executive enforces law, judicial interprets law.',[['legislative','congress'],['make','pass'],['executive','president'],['enforce','carry out'],['judicial','court'],['interpret']],URL.branches,5),
A('q11',11,'CS 13 • Legislative Checks','Give two ways Congress can check the president.','Find legislative checks on the executive. Choose two: override vetoes, impeach/remove officers, approve appointments, or approve treaties.',[['override','impeach','remove','appointment','confirm','treaty'],['president','executive']],URL.checks),
A('q12',12,'CS 13 • Legislative Checks','How does Congress check the judicial branch?','Choose one Ohio example: impeach/remove federal judges or propose constitutional amendments.',[['judge','judicial','court'],['impeach','remove','amendment','propose']],URL.checks),
A('q13',13,'CS 13 • Executive Checks','How does the president check Congress?','Find the executive check on legislation: the president may veto a bill.',[['veto'],['bill','law','legislation']],URL.checks),
A('q14',14,'CS 13 • Executive Checks','Give two ways the president checks or influences the judicial branch.','Choose two Ohio examples: nominate federal judges and grant pardons or reprieves.',[['nominate','appoint'],['judge'],['pardon','reprieve']],URL.checks,2),
A('q15',15,'CS 13 • Judicial Checks','How can courts check Congress?','Find judicial review. Courts interpret statutes and may declare acts of Congress unconstitutional.',[['court','judicial'],['congress','law','act'],['unconstitutional','judicial review','interpret']],URL.checks,2),
A('q16',16,'CS 13 • Judicial Checks','How can courts check the president?','Courts review executive actions and may declare an executive act unconstitutional.',[['court','judicial'],['president','executive'],['unconstitutional','review','interpret']],URL.checks,2),
A('q17',17,'CS 13 • Judicial Independence','Why can the president not remove a federal judge merely for an unfavorable ruling?','Connect life tenure and separation of powers to judicial independence from presidential control.',[['independ','separation','life tenure'],['president','executive'],['remove','fire','control']],URL.checks,2),
A('q18',18,'CS 13 • Political Influences','How can an interest group influence more than one branch?','Use the interest-group page and Ohio examples: propose legislation, advocate agency rules, or file court briefs.',[['legislation','bill','congress'],['rule','agency','executive'],['brief','court','judicial']],URL.groups,2),
A('q19',19,'CS 13 • Political Influences','How can political party control affect interaction between Congress and the president?','Compare unified and divided government. Shared party control may increase cooperation; opposing control may increase conflict or negotiation.',[['party'],['congress','legislative'],['president','executive'],['cooperat','conflict','divided','unified']],URL.checks,3),
A('q20',20,'CS 13 • Political Influences','How can public interest and media coverage affect government action?','Explain that attention, reporting, and commentary can increase pressure on officials and make an issue a priority.',[['public','people','citizen'],['media','news','coverage'],['pressure','attention','priority','influence']],URL.groups,2),
A('q21',21,'CS 13 • Political Influences','What are informal relationships among members of different branches?','Explain that personal or working connections—not formal constitutional powers—can help officials cooperate or negotiate.',[['relationship','connection','working','personal'],['branch','official'],['cooperat','negotiat','influence']],URL.checks,2),
A('q22',22,'CS 12–13 • Synthesis','Why is federal policymaking described as a dynamic interaction?','Connect distinct branch roles with cooperation, checks and balances, and outside political influences.',[['branch'],['cooperat','work together'],['check','balance','limit'],['influence','interest group','party','public','media']],URL.checks,3)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
