const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";const META={title:"CS 20-21 Fiscal and Monetary Policy Intro",assignmentKey:"gov-cs20-21-intro-2026-v1"};
const URL={"fiscal":"https://www.cbo.gov/topics/budget","reg":"https://www.ftc.gov/about-ftc/mission","fed":"https://www.federalreserve.gov/monetarypolicy.htm","omo":"https://www.federalreserve.gov/monetarypolicy/openmarket.htm"};const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,"CS 20-21","What is fiscal policy?","Define it using the two government choices: taxing and spending.",[["tax"],["spend"],["government"]],URL.fiscal,2),
A('q2',2,"CS 20-21","How can fiscal policy encourage economic growth?","Look for increased government spending and/or decreased taxes.",[["increase","more","raise"],["spend"],["decrease","lower","cut"],["tax"]],URL.fiscal,2),
A('q3',3,"CS 20-21","How can fiscal policy slow economic growth?","Use decreased spending and/or increased taxes.",[["decrease","less","cut"],["spend"],["increase","raise","higher"],["tax"]],URL.fiscal,2),
A('q4',4,"CS 20-21","Why might a tax cut encourage growth?","Connect lower taxes to more money available for household spending or business investment.",[["money","income","revenue"],["spend","invest","business","consumer"]],URL.fiscal,2),
A('q5',5,"CS 20-21","Why might increased government spending encourage growth?","Connect public purchases or programs to demand, jobs, or income.",[["demand","purchase","program"],["job","income","growth"]],URL.fiscal,2),
A('q6',6,"CS 20-21","What is one benefit of economic regulation?","Use consumer protection or prevention of unfair business practices.",[["consumer","buyer","public"],["protect","safe","unfair","deceptive"]],URL.reg,2),
A('q7',7,"CS 20-21","What is one possible cost of regulation?","Identify compliance costs, reduced corporate profits, or slower growth.",[["cost","profit","growth"],["business","corporate","econom"]],URL.reg,2),
A('q8',8,"CS 20-21","Why must policymakers weigh both regulatory benefits and costs?","Explain that protection can help the public while compliance can burden firms or growth.",[["benefit","protect"],["cost","burden","profit","growth"],["balance","weigh"]],URL.reg,2),
A('q9',9,"CS 20-21","What is monetary policy?","Define it as Federal Reserve actions affecting money and credit.",[["federal reserve","fed"],["money","credit"],["action","policy"]],URL.fed,2),
A('q10',10,"CS 20-21","How does lowering interest rates tend to affect growth?","Lower borrowing costs can encourage loans, purchases, and investment.",[["borrow","loan"],["purchase","spend","invest"],["encourage","increase","growth"]],URL.fed,2),
A('q11',11,"CS 20-21","How does raising interest rates tend to affect growth?","Higher borrowing costs discourage loans and spending, slowing activity.",[["borrow","loan"],["discourage","reduce","less"],["spend","invest","growth"]],URL.fed,2),
A('q12',12,"CS 20-21","How can the reserve requirement encourage growth?","The Fed lowers it so banks can lend more money.",[["lower","decrease"],["bank"],["lend","loan","more"]],URL.fed,2),
A('q13',13,"CS 20-21","What happens when the Fed buys government bonds?","Money enters the banking system, supporting lending and lower rates.",[["buy","purchase"],["money","bank"],["lend","rate","growth"]],URL.omo,2),
A('q14',14,"CS 20-21","What happens when the Fed sells government bonds?","Money leaves the banking system, limiting lending and slowing growth.",[["sell"],["money","bank"],["less","limit","slow","lending"]],URL.omo,2),
A('q15',15,"CS 20-21","What is the main difference between fiscal and monetary policy?","Fiscal uses taxing/spending by elected government; monetary uses Fed tools affecting money and credit.",[["fiscal"],["tax","spend"],["monetary"],["federal reserve","fed"],["money","credit","interest"]],URL.fed,2),
A('q16',16,"CS 20-21","The economy is growing too quickly. Choose one fiscal and one monetary response.","Use higher taxes or lower spending plus higher rates, bond sales, or higher reserve requirements.",[["tax","spend"],["rate","bond","reserve"],["higher","increase","lower","decrease","sell"]],URL.fed,2)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
