const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";const META={title:"CS 16-17 Ohio Government and Citizenship Intro",assignmentKey:"gov-cs16-17-intro-2026-v1"};
const URL={"ohio":"https://www.legislature.ohio.gov/laws/ohio-constitution","us":"https://constitutioncenter.org/the-constitution","ballot":"https://www.ohiosos.gov/legislation-and-ballot-issues/putting-an-issue-on-the-ballot/","courts":"https://www.supremecourt.ohio.gov/courts/judicial-system/"};const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,"CS 16-17","What five basic principles appear in both the Ohio and U.S. Constitutions?","List separation of powers, checks and balances, limited government, a bill of rights, and popular sovereignty.",[["separation"],["checks"],["limited"],["bill of rights"],["popular sovereignty"]],URL.ohio,2),
A('q2',2,"CS 16-17","How does separation of powers organize both governments?","Look for three branches and explain that each has a different main job.",[["three","3"],["legislative"],["executive"],["judicial"]],URL.ohio,2),
A('q3',3,"CS 16-17","What do checks and balances prevent?","Explain how branch powers keep one branch from becoming too powerful.",[["branch"],["power"],["limit","check","prevent"]],URL.us,2),
A('q4',4,"CS 16-17","How does popular sovereignty appear in Ohio government?","Connect the people to elections and direct voting on issues.",[["people","citizen","voter"],["election","vote"]],URL.ohio,2),
A('q5',5,"CS 16-17","What is an initiative in Ohio?","On the ballot page, find how citizens propose a statute or constitutional amendment.",[["citizen","people","voter"],["propose","place"],["law","statute","amendment"],["ballot"]],URL.ballot,2),
A('q6',6,"CS 16-17","What is a referendum?","Find the process in which voters approve or reject a law.",[["voter","people"],["approve","reject"],["law"]],URL.ballot,2),
A('q7',7,"CS 16-17","How are Ohio judges selected differently from federal judges?","Ohio voters elect judges; the president nominates and Senate confirms federal judges.",[["ohio"],["elect","voter"],["federal"],["appoint","nominate","confirm"]],URL.courts,2),
A('q8',8,"CS 16-17","How do legislative term limits differ in Ohio and Congress?","Ohio legislators have term limits; members of Congress do not.",[["ohio"],["term limit"],["congress","federal"],["no","not"]],URL.ohio,2),
A('q9',9,"CS 16-17","Name three major changes in Ohio’s 1851 Constitution.","Look for elected executive officials and judges, district courts, and state-debt limits.",[["elect"],["judge","executive"],["district court"],["debt"]],URL.ohio,2),
A('q10',10,"CS 16-17","Why did Ohio place limits on state debt in 1851?","Connect the rule to controlling borrowing and protecting public finances.",[["debt","borrow"],["limit","control"],["finance","taxpayer","money"]],URL.ohio,2),
A('q11',11,"CS 16-17","Give two ways a citizen can assist Ohio state government.","Choose taxes, National Guard service, running for office, voting, or ballot petitions.",[["tax","guard","office","vote","petition"],["state","ohio"]],URL.ohio,2),
A('q12',12,"CS 16-17","How can petitions affect an Ohio ballot?","Explain that enough valid signatures can place an issue or candidate before voters.",[["signature","petition"],["ballot"],["issue","candidate"]],URL.ballot,2),
A('q13',13,"CS 16-17","Give two ways citizens can assist local government.","Choose civic activities, local office, public meetings, community watch, or volunteer fire service.",[["meeting","watch","fire","office","civic","volunteer"],["local","community"]],URL.ohio,2),
A('q14',14,"CS 16-17","Why should citizens attend board or commission meetings?","Connect attendance to learning about decisions and providing public input.",[["learn","information","know"],["input","comment","speak"],["decision"]],URL.ohio,2),
A('q15',15,"CS 16-17","What is one similarity and one difference between Ohio and federal judges?","Both belong to judicial branches; Ohio elects judges while federal judges are appointed.",[["judicial","court","judge"],["ohio"],["elect"],["federal"],["appoint","nominate"]],URL.courts,2),
A('q16',16,"CS 16-17","Which citizen action would you choose to improve a local issue, and why?","Name a local action and clearly connect it to the problem it could address.",[["because","so that","would help"],["meeting","office","watch","volunteer","civic","petition"]],URL.ohio,2)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
