const GOV_SCRIPT_URL="https://script.google.com/macros/s/AKfycbx7A9pyMXnW9Zk9Ek-A05-mYdQrJB973hQTPpcfV2TLUlbJv1ZH5WEIoh9qCv8CnYTm/exec";
function launchMasteryGame(config){
 const app=document.getElementById('app'),legacyKey=config.assignmentKey+'::v1';
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[],activeSeconds:0,awaySeconds:0,tabLeaves:0,copies:0,pastes:0,questionSeconds:{},lastTick:Date.now(),runId:''};
 let cloudTimer=null,lastLocalSave=0,lastCloudSave=0;
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'00:00';const sec=Math.floor(((S.end||new Date())-S.start)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
 function balancedPositions(count){let positions=Array.from({length:count},(_,i)=>i%4);do{positions=shuffle(positions)}while(positions.some((v,i)=>i>1&&v===positions[i-1]&&v===positions[i-2]));return positions}
 function fresh(){const ordered=shuffle(config.questions),positions=balancedPositions(ordered.length);S.items=ordered.map((q,i)=>{const choices=shuffle(q.choices.filter(choice=>choice!==q.answer));choices.splice(positions[i],0,q.answer);const id=q.id||String(q.term||`q${i+1}`).toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');return{...q,id,choices,missed:false,mastered:false}});S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.events=[];S.activeSeconds=0;S.awaySeconds=0;S.tabLeaves=0;S.copies=0;S.pastes=0;S.questionSeconds={};S.lastTick=Date.now();S.runId=`run-${Date.now()}-${Math.random().toString(36).slice(2,8)}`}
 function identity(){return{name:S.name,period:S.period,email:S.email}}
 function storageKey(mail=S.email){return`${config.assignmentKey}::v2::${String(mail||'').trim().toLowerCase()}`}
 function serializableState(){return{...identity(),started:S.started,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),end:S.end?.toISOString()||'',events:S.events,activeSeconds:S.activeSeconds,awaySeconds:S.awaySeconds,tabLeaves:S.tabLeaves,copies:S.copies,pastes:S.pastes,questionSeconds:S.questionSeconds,runId:S.runId}}
 function save(){if(!S.email)return;localStorage.setItem(storageKey(),JSON.stringify(serializableState()));lastLocalSave=Date.now()}
 function restore(mail){try{let raw=localStorage.getItem(storageKey(mail));if(!raw){const legacy=localStorage.getItem(legacyKey);if(legacy){const old=JSON.parse(legacy);if(String(old.email||'').toLowerCase()===mail)raw=legacy}}if(!raw)return false;const d=JSON.parse(raw);if(String(d.email||'').toLowerCase()!==mail)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null,end:d.end?new Date(d.end):null,lastTick:Date.now()});return true}catch{return false}}
 function tick(){const now=Date.now(),sec=Math.min(15,Math.max(0,(now-S.lastTick)/1000));if(S.started){if(document.hidden)S.awaySeconds+=sec;else S.activeSeconds+=sec;const q=S.items[S.index];if(q)S.questionSeconds[q.id]=(S.questionSeconds[q.id]||0)+sec}S.lastTick=now}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,question:S.items[S.index]?.id||'',...extra});save()}
 function payload(status,resetRequested=false){tick();const mastered=S.items.filter(q=>q.mastered),first=S.items.filter(q=>q.mastered&&!q.missed).length,answers={},accepted={};mastered.forEach(q=>{answers[q.id]=q.answer;accepted[q.id]=true});return{action:status==='submitted'?'submit':'save',status,resetRequested,course:'GOV',assignmentKey:config.assignmentKey,assignmentId:config.assignmentKey,assignmentTitle:config.title,...identity(),score:first,total:S.items.length,totalPoints:S.items.length,percent:Math.round(first/S.items.length*100),answerCount:mastered.length,wrongAttempts:S.attempts-mastered.length,attempts:S.attempts,answers,accepted,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',runId:S.runId,telemetry:{activeSeconds:Math.round(S.activeSeconds),awaySeconds:Math.round(S.awaySeconds),tabLeaves:S.tabLeaves,copies:S.copies,pastes:S.pastes,questionTimes:S.questionSeconds,events:S.events,sessionId:S.runId,sessionCount:1},gameState:serializableState(),firstTryCorrect:first}}
 function post(status='in_progress',resetRequested=false){if(!GOV_SCRIPT_URL||!S.email)return;save();const data=payload(status,resetRequested);fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:new URLSearchParams({action:data.action,payload:JSON.stringify(data)})}).then(()=>{lastCloudSave=Date.now();const n=document.getElementById('saveNote');if(n)n.textContent='Saved on this Chromebook; cloud save request sent.'}).catch(()=>{const n=document.getElementById('saveNote');if(n)n.textContent='Saved on this Chromebook; cloud save request could not be sent.'})}
 function queuePost(status='in_progress'){clearTimeout(cloudTimer);cloudTimer=setTimeout(()=>post(status),750)}
 function launch(){const n=document.getElementById('name').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!/^\S+@\S+\.\S+$/.test(e)){document.getElementById('status').textContent='Enter your name, period, and a valid school email.';return}S.name=n;S.period=p;S.email=e;S.started=true;fresh();log('start');post('in_progress');render();startTimer()}
 function resume(){const mail=document.getElementById('email').value.trim().toLowerCase();if(!mail){document.getElementById('status').textContent='Enter the same school email used when saving.';return}if(restore(mail)&&S.started){render();startTimer();return}const status=document.getElementById('status');status.textContent='Looking for saved work…';const cb='loadGame_'+Date.now();window[cb]=r=>{try{const p=r&&r.found&&r.payload;if(!p||!p.gameState){status.textContent='No saved run was found for that email.';return}Object.assign(S,p.gameState,{name:p.name||'',period:p.period||'',email:p.email||mail,start:new Date(p.gameState.start),end:p.gameState.end?new Date(p.gameState.end):null,started:true,lastTick:Date.now()});save();render();startTimer()}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=GOV_SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(config.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();s.onerror=()=>status.textContent='Cloud retrieval was blocked. No local run was found.';document.body.appendChild(s)}
 function startTimer(){if(S.timer)clearInterval(S.timer);S.lastTick=Date.now();S.timer=setInterval(()=>{tick();const x=document.getElementById('clock');if(x)x.textContent=elapsed();if(Date.now()-lastLocalSave>15000)save();if(Date.now()-lastCloudSave>30000)queuePost()},1000)}
 function choose(btn,value){const q=S.items[S.index];if(q.mastered)return;S.attempts++;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('wrong'));if(value!==q.answer){q.missed=true;btn.classList.add('wrong');document.getElementById('feedback').className='feedback show hint';document.getElementById('feedback').innerHTML=`<b>Hint</b>${esc(q.hint)}`;log('incorrect',{area:q.area,choice:value});queuePost();return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').className='feedback show good';document.getElementById('feedback').innerHTML=`<b>Correct</b>${esc(q.explain)}`;log('correct',{area:q.area,firstTry:!q.missed});queuePost();setTimeout(()=>{S.index++;save();render()},config.linger||3500)}
 function restart(confirmFirst=false){if(confirmFirst&&!window.confirm('Restart the full assignment? Your name, period, and email will be kept, but your current score and question progress will be cleared.'))return;if(S.timer)clearInterval(S.timer);fresh();log('restart');post('in_progress',true);render();startTimer()}
 function finish(){if(S.timer)clearInterval(S.timer);tick();S.end=new Date();const first=S.items.filter(q=>!q.missed).length,perfect=first===S.items.length,pct=S.attempts?Math.round(S.items.length/S.attempts*100):100;log('finish',{perfect});post(perfect?'submitted':'needs_retry');save();app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="result"><div class="kicker">${perfect?'Mastery Ticket Earned':'Review Complete • Ticket Locked'}</div><h1>${esc(config.title)}</h1><p class="sub">${perfect?'Perfect first-try mastery. Show this ticket to your teacher.':'You corrected every item, but a perfect first-try run is required to earn the mastery ticket. Review the missed terms and restart.'}</p><div class="stats"><span class="stat">Accuracy: ${pct}%</span><span class="stat">First try: ${first}/${S.items.length}</span><span class="stat">Attempts: ${S.attempts}</span><span class="stat">Active time: ${formatSeconds(S.activeSeconds)}</span></div><div class="ticket ${perfect?'':'locked'}"><h2>${perfect?'Completion Ticket':'Ticket Locked'}</h2><p><b>${esc(S.name)}</b> • Period ${esc(S.period)}<br>${esc(config.title)}<br>${new Date().toLocaleString()}<br>${perfect?'Status: 100% PERFECT RUN':'Status: Restart required'}</p></div><button class="btn" id="restart">Restart Full Game</button></section>`;document.getElementById('restart').onclick=()=>restart(false)}
 function formatSeconds(value){const sec=Math.max(0,Math.floor(value||0)),h=Math.floor(sec/3600),m=Math.floor(sec%3600/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
 function render(){if(!S.started){app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="hero"><div class="kicker">Legend Mastery Series • American Government</div><h1>${esc(config.title)}</h1><p class="sub">${esc(config.subtitle)}</p><div class="pills"><span class="pill">${config.questions.length} questions</span><span class="pill">Hint after a miss</span><span class="pill">Auto-check</span><span class="pill">100% perfect run required</span></div><p class="sub">You may use a hint and correct a missed item to finish the review, but the mastery certificate is earned only by answering every question correctly on the first attempt in one complete run.</p></section><section class="panel"><div class="identity"><label>Name<input id="name" autocomplete="name"></label><label>Period<select id="period"><option value="">Choose…</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><button class="btn" id="start">Start Assignment</button> <button class="btn secondary" id="resume">Retrieve Saved Run</button><div class="status" id="status"></div></section>`;document.getElementById('start').onclick=launch;document.getElementById('resume').onclick=resume;return}if(S.index>=S.items.length){finish();return}const q=S.items[S.index],mastered=S.items.filter(x=>x.mastered).length,first=S.items.filter(x=>x.mastered&&!x.missed).length,acc=S.attempts?Math.round(mastered/S.attempts*100):100;app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="question"><div class="topline"><div><div class="area">${esc(q.area)}</div><b>Question ${S.index+1} of ${S.items.length}</b></div><div class="stats"><span class="stat">First try ${first}/${S.items.length}</span><span class="stat">Accuracy ${acc}%</span><span class="stat" id="clock">${elapsed()}</span></div></div><div class="progress"><div style="width:${mastered/S.items.length*100}%"></div></div><div class="stem">${esc(q.stem)}</div><div class="choices">${q.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="feedback" class="feedback"></div><div class="status" id="saveNote"></div><button class="btn" id="saveNow" type="button">Save Progress</button> <button class="btn secondary" id="restartNow" type="button">Restart Assignment</button></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value));document.getElementById('saveNow').onclick=()=>{save();document.getElementById('saveNote').textContent='Saved on this Chromebook; sending cloud save request…';post('in_progress')};document.getElementById('restartNow').onclick=()=>restart(true)}
 render();window.addEventListener('beforeunload',()=>{tick();save()});document.addEventListener('visibilitychange',()=>{if(!S.started)return;if(document.hidden)S.tabLeaves++;log(document.hidden?'tab_leave':'tab_return');if(document.hidden)queuePost()});document.addEventListener('copy',()=>{if(S.started){S.copies++;log('copy')}});document.addEventListener('paste',()=>{if(S.started){S.pastes++;log('paste')}});
}

const conciseAnswers={
 'popular sovereignty':'power comes from the people','consent of the governed':'citizens permit government to rule','limited government':'government power is restricted by law','rule of law':'everyone must obey the law','federalism':'national and state governments share power','separation of powers':'government powers are split among branches','checks and balances':'each branch can restrain the others','judicial branch':'the branch that interprets laws','reserved powers':'powers kept by the states','Tenth Amendment':'protects powers kept by the states','Federalists':'favored Constitution ratification','Anti-Federalists':'opposed Constitution ratification','ratification':'formal approval','Bill of Rights':'the first ten amendments','Necessary and Proper Clause':'supports Congress’s implied powers','Supremacy Clause':'federal law overrides state law','enumerated powers':'specifically listed powers','implied powers':'powers inferred from listed powers','formal amendment':'an official constitutional change','Article V':'the amendment process','judicial review':'courts review constitutionality','Marbury v. Madison':'the case establishing judicial review','legislation':'laws enacted by Congress','legislative oversight':'Congress monitors the executive branch','Civil Rights Act of 1964':'bans discrimination in employment','Voting Rights Act of 1965':'targets unfair voting barriers','living document':'the Constitution adapts over time','adequately':'enough to meet the need','excessive':'more than reasonable or necessary','diminished':'reduced or weakened'
};
const q=(area,term,definition,wrong,hint,explain)=>{const answer=conciseAnswers[term]||definition;return{area,term,stem:`Which definition best matches ${term}?`,answer,choices:[answer,...wrong],hint,explain}};
const questions=[
q('CS 5 • Principles','popular sovereignty','government authority comes from the people',['government power belongs only to judges','states may ignore the Constitution','officials may act without limits'],'Who is the original source of political power?','Popular sovereignty means the people are the source of government authority.'),
q('CS 5 • Principles','consent of the governed','the people give government permission to rule',['Congress approves every court ruling','states control all national powers','the president chooses all voters'],'Think permission from citizens.','Legitimate government rests on the permission of the people.'),
q('CS 5 • Principles','limited government','government may use only powers allowed by law and the Constitution',['government has unlimited emergency power','only state governments must obey laws','citizens may cancel any law individually'],'Constitutional boundaries are the key.','Limited government restricts what public officials may do.'),
q('CS 5 • Principles','rule of law','laws apply to everyone, including government officials',['judges create any law they want','only voters must obey laws','the executive branch controls elections'],'No person stands above the law.','Rule of law requires both citizens and officials to follow established laws.'),
q('CS 5 • Principles','federalism','power is divided between national and state governments',['power is divided among three national branches','all power belongs to local governments','courts hold all government power'],'Think levels of government.','Federalism divides governing power between the national government and the states.'),
q('CS 5 • Principles','separation of powers','legislative, executive, and judicial powers belong to different branches',['national and state governments share power','citizens vote directly on every law','states may overrule federal courts'],'Think branches, not levels.','Separation of powers assigns major functions to different branches.'),
q('CS 5 • Principles','checks and balances','each branch can limit certain actions of the other branches',['each state receives the same population','courts write the federal budget','the president controls every branch'],'A veto and Senate confirmation are examples.','Checks and balances keep any one branch from becoming too powerful.'),
q('CS 5 • Structure','legislative branch','the branch that makes federal laws',['the branch that carries out federal laws','the branch that interprets laws','the level that issues local licenses'],'Think Congress.','Congress is the legislative branch and makes federal laws.'),
q('CS 5 • Structure','executive branch','the branch that carries out and enforces federal laws',['the branch that writes constitutional amendments alone','the branch that interprets laws','the level that ratifies every treaty'],'Think President and agencies.','The executive branch carries out and enforces federal laws.'),
q('CS 5 • Structure','judicial branch','the branch that interprets laws and resolves constitutional disputes',['the branch that collects all state taxes','the branch that commands Congress','the branch that proposes every amendment'],'Think federal courts.','The judicial branch interprets laws and the Constitution.'),
q('CS 5 • Federalism','reserved powers','powers kept by the states or the people',['powers given only to Congress','powers shared by all three branches','powers held only during war'],'The Tenth Amendment is the clue.','Reserved powers are not delegated to the United States and remain with states or the people.'),
q('CS 5 • Federalism','Tenth Amendment','the amendment emphasizing powers reserved to states or the people',['the amendment creating judicial review','the amendment lowering the voting age','the amendment ending slavery'],'Its Roman numeral is X.','The Tenth Amendment supports the federal system by recognizing reserved powers.'),
q('CS 6 • Ratification','Federalists','supporters of ratifying the Constitution and a stronger national government',['opponents who demanded state supremacy','delegates who wanted to keep the Articles unchanged','judges who opposed all national courts'],'Think support for the proposed Constitution.','Federalists supported ratification and stronger national authority.'),
q('CS 6 • Ratification','Anti-Federalists','opponents of ratification who feared centralized power and wanted rights protected',['supporters of the Supremacy Clause','writers who opposed state power','officials who wanted no amendments'],'Think fear of a too-powerful national government.','Anti-Federalists opposed ratification without stronger protections for liberty and states.'),
q('CS 6 • Ratification','ratification','formal approval of the Constitution or an amendment',['a court declaring a law unconstitutional','Congress investigating an agency','the president rejecting a bill'],'Think official approval.','Ratification is the formal approval needed for a constitution or amendment.'),
q('CS 6 • Ratification','Bill of Rights','the first ten amendments protecting individual liberties',['the first ten articles creating Congress','all Supreme Court opinions','the list of powers denied to states only'],'Anti-Federalists demanded it.','The Bill of Rights added written protections for individual freedoms.'),
q('CS 6 • National power','Necessary and Proper Clause','authority for Congress to make laws needed to carry out its listed powers',['a rule requiring identical state laws','the amendment process','a ban on national courts'],'It is also called the elastic clause.','The clause supports implied powers needed to execute Congress’s enumerated powers.'),
q('CS 6 • National power','Supremacy Clause','the Constitution and valid federal laws take priority over conflicting state laws',['the president is above the courts','states may cancel federal laws','Congress may change court verdicts'],'Think national law versus conflicting state law.','The Supremacy Clause makes valid federal law the supreme law of the land.'),
q('CS 6 • National power','enumerated powers','powers specifically listed in the Constitution',['powers invented by courts','powers kept only by states','powers used only by local government'],'Enumerated means listed.','Enumerated powers are expressly granted, such as taxing and regulating interstate commerce.'),
q('CS 6 • National power','implied powers','powers reasonably inferred from listed powers',['powers forbidden by the Bill of Rights','powers reserved only to states','powers used before the Constitution'],'Think Necessary and Proper Clause.','Implied powers help Congress carry out its enumerated responsibilities.'),
q('CS 7 • Constitutional change','formal amendment','an official change made through the Article V process',['a tradition followed by presidents','a Supreme Court explanation','an agency regulation'],'Think proposal and ratification.','A formal amendment changes the written Constitution through Article V.'),
q('CS 7 • Constitutional change','Article V','the constitutional process for proposing and ratifying amendments',['the article establishing the presidency','the clause establishing federal supremacy','the amendment reserving state powers'],'It answers how the text is officially changed.','Article V establishes the formal amendment process.'),
q('CS 7 • Constitutional change','judicial review','court authority to determine whether laws or government actions are constitutional',['Congress watching executive agencies','states approving amendments','the president vetoing legislation'],'Think Marbury v. Madison.','Judicial review lets courts evaluate government action against the Constitution.'),
q('CS 7 • Constitutional change','Marbury v. Madison','the case associated with establishing judicial review',['the case ending school segregation','the law ending employment discrimination','the amendment lowering the voting age'],'This 1803 case involved Chief Justice Marshall.','Marbury v. Madison established the principle of judicial review.'),
q('CS 7 • Constitutional change','legislation','laws passed by Congress that add detail to the constitutional framework',['customs that are never written','court decisions that amend Article V','state refusals to follow federal law'],'Think statutes such as civil-rights laws.','Congress uses legislation to turn broad constitutional authority into specific policies.'),
q('CS 7 • Constitutional change','legislative oversight','Congress monitoring and investigating executive agencies and programs',['the Supreme Court reviewing a conviction','states ratifying an amendment','the president nominating a judge'],'Think a congressional hearing.','Oversight is an informal practice Congress uses to check administration of the laws.'),
q('CS 7 • Constitutional change','Civil Rights Act of 1964','a federal law prohibiting discrimination in major areas of public life and employment',['an amendment lowering the voting age','a case creating judicial review','a law creating the Articles of Confederation'],'Think desegregation and employment equality.','The act used congressional power to enforce civil-rights protections.'),
q('CS 7 • Constitutional change','Voting Rights Act of 1965','a federal law targeting discriminatory barriers to voting',['a clause expanding implied powers','a decision approving segregation','an amendment creating the Senate'],'Think literacy tests and unequal access to the ballot.','The act strengthened federal protection of voting rights.'),
q('CS 7 • Constitutional change','living document','the idea that constitutional government adapts through amendments, interpretation, laws, and practices',['the Constitution automatically expires','officials may ignore the written text','states may rewrite federal laws'],'Think change over time using lawful methods.','The Constitution endures while its application develops through recognized methods of change.'),
q('State Test Language','adequately','enough or sufficiently to meet the need',['quickly and without discussion','according to an old tradition','equally between every group'],'If something is adequate, it is enough for its purpose.','In a released question, “adequately protect” means protect well enough to meet the need.'),
q('State Test Language','excessive','more than is reasonable, necessary, or acceptable',['required by the Constitution','shared equally by two governments','reduced from an earlier amount'],'Think too much—not simply strong or important.','In a released question, “excessive government power” means more government power than is reasonable or acceptable.'),
q('State Test Language','diminished','reduced, weakened, or made less',['formally approved by voters','divided into separate branches','expanded beyond its previous limit'],'Think made smaller or less powerful.','In a released question, “diminished powers of the states” means state powers were reduced or weakened.')
];
launchMasteryGame({title:'CS 5–7 Constitutional Principles Vocabulary',subtitle:'Build the essential language for constitutional principles, ratification, and constitutional change.',assignmentKey:'gov-cs5-7-vocabulary-2026-v1',questions,linger:3200});
