const Q=(area,term,definition,wrong,hint,explain)=>({area,stem:`Which definition best matches ${term}?`,answer:definition,choices:[definition,...wrong],hint,explain});
const W=['a power exercised only by state courts','a method for passing ordinary legislation','a protection found only in the original Constitution'];
const questions=[
Q('CS 9 • Reconstruction','Reconstruction Amendments','the Thirteenth, Fourteenth, and Fifteenth Amendments',W,'Think the three amendments adopted after the Civil War.','Amendments 13–15 are collectively known as the Reconstruction Amendments.'),
Q('CS 9 • Reconstruction','Thirteenth Amendment','the amendment that abolished slavery and involuntary servitude except as punishment for crime',W,'Think emancipation.','The Thirteenth Amendment constitutionally abolished slavery.'),
Q('CS 9 • Reconstruction','Fourteenth Amendment','the amendment establishing birthright citizenship and protecting due process and equal protection',W,'Think citizenship and equality.','The Fourteenth Amendment provides citizenship, due process, and equal protection.'),
Q('CS 9 • Reconstruction','Fifteenth Amendment','the amendment prohibiting denial of voting rights because of race color or previous servitude',W,'Think race and voting.','The Fifteenth Amendment constitutionally protected voting rights regardless of race.'),
Q('CS 9 • Reconstruction','birthright citizenship','citizenship held by persons born in the United States',W,'Focus on the word born.','The Fourteenth Amendment defines citizenship for persons born or naturalized in the United States.'),
Q('CS 9 • Reconstruction','naturalization','the legal process by which a noncitizen becomes a citizen',W,'Think becoming a citizen after birth.','The Fourteenth Amendment includes citizens who are naturalized.'),
Q('CS 9 • Reconstruction','due process','the requirement that government use fair legal procedures before depriving life liberty or property',W,'Think fair legal treatment.','The Fourteenth Amendment prohibits states from denying due process.'),
Q('CS 9 • Reconstruction','equal protection','the requirement that states provide equal protection of the laws to all persons',W,'Think equal treatment under law.','The Equal Protection Clause is part of the Fourteenth Amendment.'),
Q('CS 9 • Reconstruction','previous condition of servitude','a person’s former status as an enslaved person',W,'Servitude refers to enslavement.','The Fifteenth Amendment forbids voting discrimination based on former enslavement.'),
Q('CS 9 • Continued struggle','Jim Crow laws','state and local laws that enforced racial segregation and inequality',W,'Think segregation after Reconstruction.','Jim Crow laws limited African American equality despite the Reconstruction Amendments.'),
Q('CS 9 • Continued struggle','racial segregation','the enforced separation of people by race',W,'Think separate facilities and institutions.','Jim Crow used segregation to maintain racial inequality.'),
Q('CS 10 • Suffrage','suffrage','the right to vote',W,'This word means voting rights.','Suffrage is the right to participate in elections by voting.'),
Q('CS 10 • Suffrage','disenfranchisement','the denial or removal of the right to vote',W,'Think being blocked from voting.','Disenfranchisement prevents an eligible group from exercising suffrage.'),
Q('CS 10 • Suffrage','Nineteenth Amendment','the amendment prohibiting denial of voting rights based on sex',W,'Think women’s suffrage.','The Nineteenth Amendment constitutionally protected voting rights regardless of sex.'),
Q('CS 10 • Suffrage','Twenty-fourth Amendment','the amendment prohibiting poll taxes in federal elections',W,'Think voting fees.','The Twenty-fourth Amendment eliminated poll taxes in federal elections.'),
Q('CS 10 • Suffrage','Twenty-sixth Amendment','the amendment protecting voting rights for citizens age eighteen and older',W,'Think the voting age.','The Twenty-sixth Amendment lowered the voting age to 18.'),
Q('CS 10 • Suffrage','poll tax','a fee required as a condition for voting',W,'A tax became a voting barrier.','Poll taxes especially burdened poor voters and were used to suppress African American voting.'),
Q('CS 11 • Electoral College','Electoral College','the state-based system used to formally select the president and vice president',W,'Think electoral votes rather than one direct national count.','Presidents are formally selected through electoral votes from the states.'),
Q('CS 11 • Electoral College','electoral vote','a formal vote cast for president and vice president through the Electoral College',W,'States receive a number of these votes.','Candidates compete for state electoral votes.'),
Q('CS 11 • Electoral College','electoral majority','more than half of all appointed electoral votes',W,'A candidate must win a majority.','A presidential candidate needs a majority of electoral votes to secure the presidency.'),
Q('CS 11 • Electoral College','state electoral-vote total','the number equal to a state’s U.S. representatives plus its two senators',W,'Add House seats and Senate seats.','Representation in Congress determines each state’s electoral-vote total.'),
Q('CS 11 • Presidency','Twelfth Amendment','the amendment requiring separate electoral ballots for president and vice president',W,'Think separate ballots.','The Twelfth Amendment changed Electoral College voting to avoid earlier tie problems.'),
Q('CS 11 • Presidency','Twenty-second Amendment','the amendment limiting a president to two elected terms',W,'Think presidential term limits.','The Twenty-second Amendment restricts presidential tenure.'),
Q('CS 11 • Presidency','Twenty-third Amendment','the amendment granting presidential electors to the District of Columbia',W,'Think Washington, D.C.','The Twenty-third Amendment gave D.C. participation in presidential elections.'),
Q('CS 11 • Presidency','Twenty-fifth Amendment','the amendment addressing presidential succession and disability',W,'Think vacancy or inability.','The Twenty-fifth Amendment provides procedures for succession and presidential inability.'),
Q('CS 11 • Presidency','presidential succession','the process determining who assumes presidential powers after a vacancy',W,'Who takes over?','Succession provides continuity when a president dies, resigns, or is removed.'),
Q('CS 11 • Presidency','presidential disability','a president’s inability to discharge the powers and duties of office',W,'Think inability rather than an election loss.','The Twenty-fifth Amendment addresses temporary or continuing presidential inability.'),
Q('CS 11 • Presidency','vice-presidential vacancy','a situation in which the office of vice president is empty',W,'The Twenty-fifth Amendment supplies a procedure.','A president nominates a new vice president, subject to confirmation by both houses of Congress.')
];
launchMasteryGame({title:'CS 9–11 Amendments and the Presidency Vocabulary',subtitle:'Master Reconstruction protections, suffrage amendments, the Electoral College, and presidential amendment vocabulary.',assignmentKey:'gov-cs9-11-vocabulary-2026-v1',questions,linger:3200});
