const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
const META={title:'CS 9–11 Reconstruction Suffrage and Presidency Intro',assignmentKey:'gov-cs9-11-intro-2026-v1'};
const URL={a13:'https://www.archives.gov/milestone-documents/13th-amendment',a14:'https://www.archives.gov/milestone-documents/14th-amendment',a15:'https://www.archives.gov/milestone-documents/15th-amendment',amends:'https://www.archives.gov/founding-docs/amendments-11-27',ec:'https://www.archives.gov/electoral-college/about'};
const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,'CS 9 • Reconstruction Amendments','Which three amendments are called the Reconstruction Amendments?','Read the historical background near the top. Identify the three amendments adopted after the Civil War.',[['13','thirteenth'],['14','fourteenth'],['15','fifteenth']],URL.a13,3),
A('q2',2,'CS 9 • Reconstruction Amendments','What did the Thirteenth Amendment abolish?','Read Section 1 and find the two conditions that “shall [not] exist.” A short answer naming slavery is enough.',[['slavery','enslavement','involuntary servitude']],URL.a13),
A('q3',3,'CS 9 • Reconstruction Amendments','What exception appears in the Thirteenth Amendment?','Finish Section 1 after “except.” It permits involuntary servitude as punishment after conviction for a crime.',[['punishment','crime','convict']],URL.a13),
A('q4',4,'CS 9 • Reconstruction Amendments','How does the Fourteenth Amendment define U.S. citizenship?','Read the first sentence of Section 1. Focus on people born or naturalized in the United States.',[['born','naturalized'],['united states','u s']],URL.a14),
A('q5',5,'CS 9 • Reconstruction Amendments','What does the Fourteenth Amendment prohibit states from denying without due process?','In Section 1, find the three words immediately before “without due process of law.”', [['life'],['liberty'],['property']],URL.a14,3),
A('q6',6,'CS 9 • Reconstruction Amendments','What does equal protection require states to provide?','At the end of Section 1, find “equal protection of the laws.” Explain equal legal protection for all persons.',[['equal'],['protection','treatment'],['law','person','people']],URL.a14),
A('q7',7,'CS 9 • Reconstruction Amendments','Which voting discrimination does the Fifteenth Amendment prohibit?','Read Section 1. Name any of the listed grounds: race, color, or previous condition of servitude.',[['race','color','servitude','formerly enslaved']],URL.a15),
A('q8',8,'CS 9 • Continued Struggle','Why did the Reconstruction Amendments not create immediate equality?','Use the historical background and connect continued discrimination or Jim Crow segregation to weak or resisted enforcement.',[['jim crow','segregation','discrimination','racism'],['continued','still','enforced','resistance','denied']],URL.a14),
A('q9',9,'CS 9 • Continued Struggle','What were Jim Crow laws?','Look for the post-Reconstruction discussion. Explain that state and local laws enforced racial segregation and inequality.',[['law'],['segregation','separate'],['race','racial','african american']],URL.a14),
A('q10',10,'CS 10 • Suffrage','What does suffrage mean?','The CS 10 amendments concern access to elections. Suffrage simply means the right to vote.',[['right'],['vote','voting']],URL.amends),
A('q11',11,'CS 10 • Suffrage','Which amendment prohibited denying voting rights based on race?','Scroll to Amendment XV. Its Section 1 names race, color, and previous condition of servitude.',[['15','fifteenth']],URL.amends),
A('q12',12,'CS 10 • Suffrage','Which amendment prohibited denying voting rights based on sex?','Scroll to Amendment XIX. The Roman numeral XIX means 19.',[['19','nineteenth']],URL.amends),
A('q13',13,'CS 10 • Suffrage','Which amendment prohibited poll taxes in federal elections?','Scroll to Amendment XXIV and find “poll tax or other tax.”', [['24','twenty fourth','twenty-fourth']],URL.amends),
A('q14',14,'CS 10 • Suffrage','How did poll taxes restrict voting?','A poll tax required payment before voting. Explain why this especially blocked poor voters.',[['pay','payment','fee','tax','money'],['poor','could not afford','barrier','prevent']],URL.amends),
A('q15',15,'CS 10 • Suffrage','Which amendment protected voting rights for citizens age 18 and older?','Scroll to Amendment XXVI and find “eighteen years of age.”', [['26','twenty sixth','twenty-sixth']],URL.amends),
A('q16',16,'CS 10 • Suffrage','How did the 15th, 19th, 24th, and 26th Amendments expand participation?','Connect each amendment to removal of a voting barrier based on race, sex, poll tax, or age.',[['vote','voting','suffrage'],['expand','extend','more','barrier','protect']],URL.amends),
A('q17',17,'CS 11 • Electoral College','How is each state’s number of electoral votes determined?','Read “Allocation of Electors.” Add the state’s House representatives and its two senators.',[['representative','house'],['senator','senate']],URL.ec),
A('q18',18,'CS 11 • Electoral College','What must a candidate win to secure the presidency?','Read the overview for the required share of the total electoral votes. The key word is majority.',[['majority'],['electoral']],URL.ec),
A('q19',19,'CS 11 • Electoral College','Why does the Electoral College reflect federalism?','Use the state-based allocation. Explain that a national president is selected through electoral votes assigned to states.',[['state'],['electoral'],['federal','national','president']],URL.ec),
A('q20',20,'CS 11 • Presidential Amendments','What change did the Twelfth Amendment make?','Scroll to Amendment XII. Find the separate ballot language for President and Vice-President.',[['separate'],['president'],['vice president']],URL.amends,3),
A('q21',21,'CS 11 • Presidential Amendments','What limit did the Twenty-second Amendment establish?','Scroll to Amendment XXII. Focus on how many times a person may be elected president.',[['two','2'],['term','elected','president']],URL.amends),
A('q22',22,'CS 11 • Presidential Amendments','What did the Twenty-third Amendment grant to Washington, D.C.?','Scroll to Amendment XXIII. Look for the District constituting the seat of government and its electors.',[['district','d c','washington'],['elector','electoral vote']],URL.amends),
A('q23',23,'CS 11 • Presidential Amendments','What two major subjects are addressed by the Twenty-fifth Amendment?','Scroll to Amendment XXV. Identify presidential succession and presidential inability or disability.',[['succession','vice president becomes president','vacancy'],['disability','inability','unable']],URL.amends),
A('q24',24,'CS 11 • Presidential Amendments','How is a vacancy in the vice presidency filled under the Twenty-fifth Amendment?','Read Section 2. The president nominates someone, and both houses of Congress confirm by majority vote.',[['president'],['nominate'],['congress','house','senate'],['confirm','majority']],URL.amends,3)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
