const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
const META={title:'CS 8 Bill of Rights Intro',assignmentKey:'gov-cs8-intro-2026-v1'};
const FULL='https://constitutioncenter.org/the-constitution/full-text',OVERVIEW='https://constitutioncenter.org/bill-of-rights-resources';
const A=(id,n,section,prompt,hint,keys,link=FULL)=>({id,n,section,prompt,hint,keys,link});
const QS=[
A('q1',1,'Bill of Rights Foundations','What is the Bill of Rights?','Open the link and read the first paragraph. Identify how many amendments it contains and what they protect.',[['first ten','first 10','10 amendments','ten amendments'],['right','libert','freedom']],OVERVIEW),
A('q2',2,'Bill of Rights Foundations','Why was the Bill of Rights added to the Constitution?','Read the opening explanation. Focus on protecting liberties and limiting government power.',[['protect','guarantee','secure'],['right','libert','freedom'],['limit','government']]),
A('q3',3,'Bill of Rights Foundations','What are civil liberties?','Use the overview and explain them as freedoms protected from government interference.',[['freedom','libert','right'],['government','interference','intrusion','protect']]),
A('q4',4,'First Amendment','Name the five freedoms protected by the First Amendment.','Scroll to “First Amendment.” Copy the five ideas after “Congress shall make no law”: religion, speech, press, assembly, and petition.',[['religion'],['speech'],['press'],['assembl'],['petition']]),
A('q5',5,'First Amendment','A newspaper criticizes a new federal policy. Which First Amendment freedom protects it?','In the First Amendment, find the words “freedom ... of the press.”', [['press']]),
A('q6',6,'First Amendment','Citizens gather peacefully outside city hall. Which freedom are they using?','In the First Amendment, find “peaceably to assemble.”', [['assembl','gather']]),
A('q7',7,'First Amendment','Citizens ask Congress to change a law. Which freedom are they using?','At the end of the First Amendment, find “petition the Government.”', [['petition']]),
A('q8',8,'First Amendment','Explain one way the First Amendment protects religious liberty.','Find “establishment of religion” and “free exercise.” Explain either no government-established religion or freedom to practice religion.', [['religion','religious'],['practice','exercise','establish','government','choose']]),
A('q9',9,'Second Amendment','What right is protected by the Second Amendment?','Scroll to “Second Amendment” and find the phrase “keep and bear Arms.”', [['bear arms','keep arms','own gun','possess firearm','weapon']]),
A('q10',10,'Fourth Amendment','What does the Fourth Amendment protect people against?','Scroll to “Fourth Amendment.” The key phrase is “unreasonable searches and seizures.”', [['unreasonable'],['search','seizure']]),
A('q11',11,'Fourth Amendment','What must normally support a search warrant?','In the Fourth Amendment, read the words immediately after “no Warrants shall issue.”', [['probable cause']]),
A('q12',12,'Fourth Amendment','What must a valid warrant describe?','Finish the Fourth Amendment. It must particularly describe the place and the persons or things involved.', [['place','where','location'],['person','thing','item','seize','search']]),
A('q13',13,'Fourth Amendment','Police search a home without a warrant or emergency and have no probable cause. Which protection is most directly involved?','Match “search a home” to the amendment about unreasonable searches and warrants.', [['fourth','4th','amendment 4']]),
A('q14',14,'Fifth Amendment','What does protection against self-incrimination mean?','Scroll to “Fifth Amendment.” Find “compelled ... to be a witness against himself.”', [['not','cannot','dont','do not','refuse'],['testif','witness','against themselves','incriminate','answer']]),
A('q15',15,'Fifth Amendment','What is double jeopardy?','In the Fifth Amendment, find “same offence” and “twice put in jeopardy.”', [['same','one crime','same crime','same offense'],['twice','two times','again']]),
A('q16',16,'Fifth Amendment','What is due process?','Find “life, liberty, or property” and “due process of law.” Explain that government must follow fair legal procedures.', [['fair','proper'],['process','procedure','law']]),
A('q17',17,'Fifth Amendment','A defendant refuses to answer a question that would admit guilt. Which protection applies?','This is the Fifth Amendment protection against being forced to testify against oneself.', [['self incrimination','self-incrimination','fifth','5th']]),
A('q18',18,'Sixth Amendment','List any three rights guaranteed to a person accused of a crime by the Sixth Amendment.','Scroll to “Sixth Amendment.” Choose three: speedy/public trial, impartial jury, notice of charges, confront witnesses, obtain witnesses, or counsel.', [['speedy'],['public'],['jury'],['charges','accusation'],['confront','accuser'],['witness'],['counsel','lawyer','attorney']]),
A('q19',19,'Sixth Amendment','What does the right to counsel provide?','At the end of the Sixth Amendment, find “Assistance of Counsel for his defence.”', [['lawyer','attorney','counsel'],['defen','represent','help']]),
A('q20',20,'Sixth Amendment','Why must an accused person be informed of the charges?','Use “informed of the nature and cause of the accusation.” Explain that the person must know the accusation in order to prepare a defense.', [['know','informed','tell'],['charge','accus'],['defen','respond','prepare']]),
A('q21',21,'Sixth Amendment','A trial is delayed for many years without a valid reason. Which protection may be violated?','The first listed Sixth Amendment protection is a “speedy and public trial.”', [['speedy'],['trial','sixth','6th']]),
A('q22',22,'Eighth Amendment','Which punishments does the Eighth Amendment forbid?','Scroll to “Eighth Amendment” and find the final phrase.', [['cruel'],['unusual']]),
A('q23',23,'Eighth Amendment','The government imposes an extreme punishment grossly out of proportion to a minor offense. Which amendment is most directly involved?','Match an extreme punishment to “cruel and unusual punishments.”', [['eighth','8th','amendment 8']]),
A('q24',24,'Tenth Amendment','What happens to a power not delegated to the United States and not prohibited to the states?','Scroll to “10th Amendment.” Read after “are reserved.”', [['state','people'],['reserved','remain','kept','belong']]),
A('q25',25,'Tenth Amendment','How does the Tenth Amendment support federalism?','Connect “reserved to the States ... or to the people” to the division of power between national and state governments.', [['power'],['state'],['federal','national','divide','share','reserved']])
];
QS.find(q=>q.id==='q4').min=5;QS.find(q=>q.id==='q18').min=3;
const state={accepted:{},dirty:false},LOCAL=META.assignmentKey+'::local-v1';
const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||(q.keys.length>3?3:q.keys.length);return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: Constitution text and explanation ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
