const GOV_SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
function launchMasteryGame(config){
 const app=document.getElementById('app'),key=config.assignmentKey+'::v1';
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[]};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'00:00';const sec=Math.floor(((S.end||new Date())-S.start)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
 function fresh(){S.items=shuffle(config.questions).map(q=>({...q,choices:shuffle(q.choices),missed:false,mastered:false}));S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.events=[]}
 function identity(){return{name:S.name,period:S.period,email:S.email}}
 function save(){localStorage.setItem(key,JSON.stringify({...identity(),started:S.started,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events}))}
 function restore(){try{const d=JSON.parse(localStorage.getItem(key));if(!d)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null});return true}catch{return false}}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,...extra});save()}
 function post(status){if(!GOV_SCRIPT_URL)return;const first=S.items.filter(q=>q.mastered&&!q.missed).length,pct=Math.round(first/S.items.length*100),gameState={started:true,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events};fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,assignmentKey:config.assignmentKey,assignmentTitle:config.title,...identity(),score:first,total:S.items.length,percent:pct,attempts:S.attempts,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',elapsed:elapsed(),events:S.events,gameState})}).catch(()=>{})}
 function launch(){const n=document.getElementById('name').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!e){document.getElementById('status').textContent='Enter your name, period, and school email.';return}S.name=n;S.period=p;S.email=e;S.started=true;fresh();log('start');post('in_progress');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function resume(){const mail=document.getElementById('email').value.trim().toLowerCase();if(!mail){document.getElementById('status').textContent='Enter the same school email used when saving.';return}if(restore()&&S.started&&S.email===mail){render();startTimer();return}const status=document.getElementById('status');status.textContent='Looking for saved work…';const cb='loadGame_'+Date.now();window[cb]=r=>{try{const p=r&&r.found&&r.payload;if(!p||!p.gameState){status.textContent='No saved run was found for that email.';return}Object.assign(S,p.gameState,{name:p.name||'',period:p.period||'',email:p.email||mail,start:new Date(p.gameState.start),started:true});save();render();startTimer()}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=GOV_SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(config.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();s.onerror=()=>status.textContent='Cloud retrieval was blocked. No local run was found.';document.body.appendChild(s)}
 function startTimer(){if(S.timer)clearInterval(S.timer);S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function choose(btn,value){const q=S.items[S.index];if(q.mastered)return;S.attempts++;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('wrong'));if(value!==q.answer){q.missed=true;btn.classList.add('wrong');document.getElementById('feedback').className='feedback show hint';document.getElementById('feedback').innerHTML=`<b>Hint</b>${esc(q.hint)}`;log('incorrect',{area:q.area});return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').className='feedback show good';document.getElementById('feedback').innerHTML=`<b>Correct</b>${esc(q.explain)}`;log('correct',{area:q.area,firstTry:!q.missed});post('in_progress');setTimeout(()=>{S.index++;save();render()},config.linger||3500)}
 function restart(){if(S.timer)clearInterval(S.timer);fresh();log('restart');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function finish(){if(S.timer)clearInterval(S.timer);S.end=new Date();const first=S.items.filter(q=>!q.missed).length,perfect=first===S.items.length,pct=Math.round(first/S.items.length*100);log('finish',{perfect});post(perfect?'submitted':'needs_retry');localStorage.setItem(key,JSON.stringify({...S,end:S.end.toISOString(),start:S.start.toISOString()}));app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="result"><div class="kicker">${perfect?'Mastery Ticket Earned':'Review Complete • Ticket Locked'}</div><h1>${esc(config.title)}</h1><p class="sub">${perfect?'Perfect first-try mastery. Show this ticket to your teacher.':'You corrected every item, but a perfect first-try run is required. Review the missed areas and restart.'}</p><div class="stats"><span class="stat">Accuracy: ${pct}%</span><span class="stat">First try: ${first}/${S.items.length}</span><span class="stat">Attempts: ${S.attempts}</span><span class="stat">Time: ${elapsed()}</span></div><div class="ticket ${perfect?'':'locked'}"><h2>${perfect?'Completion Ticket':'Ticket Locked'}</h2><p><b>${esc(S.name)}</b> • Period ${esc(S.period)}<br>${esc(config.title)}<br>${new Date().toLocaleString()}<br>${perfect?'Status: 100% PERFECT RUN':'Restart required'}</p></div><button class="btn" id="restart">Restart Full Game</button></section>`;document.getElementById('restart').onclick=restart}
 function render(){if(!S.started){app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="hero"><div class="kicker">Legend Mastery Series • American Government</div><h1>${esc(config.title)}</h1><p class="sub">${esc(config.subtitle)}</p><div class="pills"><span class="pill">${config.questions.length} questions</span><span class="pill">Hint after a miss</span><span class="pill">Auto-check</span><span class="pill">100% run required</span></div></section><section class="panel"><div class="identity"><label>Name<input id="name" autocomplete="name"></label><label>Period<select id="period"><option value="">Choose…</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><button class="btn" id="start">Start Assignment</button> <button class="btn secondary" id="resume">Retrieve Saved Run</button><div class="status" id="status"></div></section>`;document.getElementById('start').onclick=launch;document.getElementById('resume').onclick=resume;return}if(S.index>=S.items.length){finish();return}const q=S.items[S.index],first=S.items.slice(0,S.index).filter(x=>!x.missed).length,acc=S.index?Math.round(first/S.index*100):100;app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="question"><div class="topline"><div><div class="area">${esc(q.area)}</div><b>Question ${S.index+1} of ${S.items.length}</b></div><div class="stats"><span class="stat">Accuracy ${acc}%</span><span class="stat" id="clock">${elapsed()}</span></div></div><div class="progress"><div style="width:${S.index/S.items.length*100}%"></div></div><div class="stem">${esc(q.stem)}</div><div class="choices">${q.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="feedback" class="feedback"></div></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value))}
 render();window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(S.started)log(document.hidden?'tab_leave':'tab_return')});document.addEventListener('copy',()=>S.started&&log('copy'));document.addEventListener('paste',()=>S.started&&log('paste'));
}
const Q=(area,stem,answer,wrong,hint,explain)=>({area,stem,answer,choices:[answer,...wrong],hint,explain});
const questions=[
Q('CS 14 • Rights','Which statement best defines a constitutional right?','a protected claim against undue government interference',['a reward granted by a business','an optional school policy','a tax collected by a city'],'Think protection from government intrusion.','Rights protect areas of liberty and participation.'),
Q('CS 14 • Participation','A citizen speaks at a council meeting. Which right supports this action?','freedom of speech',['double jeopardy','presidential succession','appellate jurisdiction'],'The citizen is expressing an opinion.','Speech protects political participation.'),
Q('CS 14 • Participation','A newspaper investigates public corruption. Which right is central?','freedom of the press',['right to bear arms','right to counsel','reserved powers'],'Think journalism.','Press freedom supports public accountability.'),
Q('CS 14 • Participation','Citizens gather peacefully to support a cause. Which right applies?','freedom of assembly',['due process only','term limits','judicial review'],'They are gathering.','Assembly protects peaceful group participation.'),
Q('CS 14 • Participation','Citizens ask legislators to change a policy. Which right applies?','right to petition',['right to jury trial','protection from search','right to pardon'],'They are making a request to government.','Petition supports direct public input.'),
Q('CS 14 • Incorporation','A state government violates a protected freedom in the Bill of Rights. Which doctrine may make that protection applicable?','incorporation',['federalism only','executive privilege','senatorial courtesy'],'Think Fourteenth Amendment due process.','Incorporation applies most Bill of Rights guarantees to states.'),
Q('CS 14 • Incorporation','Which amendment provides the due process foundation for incorporation?','Fourteenth Amendment',['Tenth Amendment','Twelfth Amendment','Twenty-second Amendment'],'This amendment also contains equal protection.','The Supreme Court uses Fourteenth Amendment due process.'),
Q('CS 14 • Responsibilities','A citizen exercises free speech while listening respectfully to disagreement. What responsibility is shown?','civil discourse',['military command','jury nullification','executive enforcement'],'Rights should respect others.','Civil discourse is a responsibility connected to speech.'),
Q('CS 14 • Responsibilities','Which responsibility is most directly connected to the right to bear arms?','receiving firearms training',['registering to vote','serving on a jury','paying a poll tax'],'Think safe exercise of the right.','Training promotes responsible firearm use.'),
Q('CS 14 • Responsibilities','Which responsibility supports the right to a jury trial?','serving on juries when called',['filing court appeals','issuing pardons','signing treaties'],'The system needs citizens as jurors.','Jury service helps provide jury trials.'),
Q('CS 14 • Responsibilities','Which actions responsibly support voting?','registering and becoming informed',['avoiding all public issues','paying a poll tax','refusing election information'],'Participation requires preparation.','Registration and informed choice support meaningful suffrage.'),
Q('CS 14 • General duties','Which is a general responsibility of citizenship?','respecting the rule of law',['ignoring taxes','denying others’ rights','avoiding responsibility'],'Everyone must follow valid law.','Rule-of-law respect is a general responsibility.'),
Q('CS 14 • General duties','Why are paying taxes and fees civic responsibilities?','they help fund government services and functions',['they eliminate constitutional rights','they select federal judges','they replace elections'],'Government services require revenue.','Taxes support public functions.'),
Q('CS 14 • Service','Which is service to the nation or state?','military service community service or public office',['private entertainment','avoiding elections','refusing every jury summons'],'Think contributions beyond personal benefit.','Citizens may serve through military, community, or office.'),
Q('CS 14 • Relative rights','Why are individual rights described as relative rather than absolute?','their exercise must be balanced with others’ rights and the common good',['government may eliminate any right','rights apply only during elections','only majorities possess rights'],'One person’s exercise can affect others.','Rights have lawful limits protecting others and society.'),
Q('CS 15 • Majority rule','What problem can arise from majority rule without minority protections?','the majority may deny rights to a smaller group',['courts lose all jurisdiction','taxes automatically disappear','presidents gain unlimited terms'],'Numbers do not erase rights.','Constitutional government balances majority decisions with minority rights.'),
Q('CS 15 • Suffrage','Which amendment extended suffrage regardless of sex?','Nineteenth Amendment',['Thirteenth Amendment','Twenty-second Amendment','Twenty-fifth Amendment'],'Think women’s suffrage.','The Nineteenth Amendment prohibited sex-based voting denial.'),
Q('CS 15 • Poll tax','Which amendment eliminated poll taxes in federal elections?','Twenty-fourth Amendment',['Fifteenth Amendment','Nineteenth Amendment','Twenty-sixth Amendment'],'Think voting fees.','The Twenty-fourth Amendment removed a financial voting barrier.'),
Q('CS 15 • Executive','Federal troops protect students integrating a public school. Which branch is acting?','executive branch',['legislative branch','judicial branch only','local legislative branch'],'The president commands federal enforcement.','Executive action helped enforce integration at Little Rock.'),
Q('CS 15 • Executive','Federal officials prosecute violations of open-housing law. Which branch role is illustrated?','executive enforcement',['judicial lawmaking','legislative appeal','state ratification'],'Prosecution carries out law.','The executive enforces civil-rights legislation.'),
Q('CS 15 • Legislative','Congress passes a law banning discrimination in public accommodations. Which branch extended rights?','legislative branch',['executive branch','judicial branch','Electoral College'],'Congress enacts statutes.','Civil rights acts are legislative action.'),
Q('CS 15 • Legislative','Congress protects access to the ballot through a federal statute. Which action is this?','Voting Rights Act legislation',['executive pardon','judicial nomination','constitutional veto'],'Think congressional voting protection.','The Voting Rights Act used legislative power.'),
Q('CS 15 • Judicial','The Supreme Court applies a Bill of Rights protection to a state. Which process is used?','incorporation',['impeachment','referendum','taxation'],'Think Fourteenth Amendment.','Incorporation extends most federal guarantees to states.'),
Q('CS 15 • Judicial','A court strikes down a discriminatory state law under equal protection. Which branch acts?','judicial branch',['executive branch','legislative branch','county commission'],'A court is interpreting the Constitution.','Judicial review and equal protection can extend civil rights.'),
Q('CS 15 • Public pressure','Why does public pressure matter in civil-rights history?','it can push government branches to protect denied rights',['it automatically amends the Constitution','it replaces every election','it removes judicial independence'],'People can demand action.','Organizing and advocacy can prompt government response.'),
Q('CS 15 • Analysis','Which example best shows executive action expanding participation?','troops enforcing school integration',['Congress passing a statute','a court interpreting equal protection','a state collecting taxes'],'Identify the president’s branch.','Federal troops were an executive enforcement action.'),
Q('CS 15 • Analysis','Which example best shows legislative action expanding civil rights?','enacting civil rights and voting rights laws',['granting a pardon','deciding a court appeal','commanding federal troops'],'Congress makes laws.','Congress enacted statutory protections.'),
Q('CS 15 • Analysis','Which example best shows judicial action expanding civil rights?','applying federal rights to states through incorporation',['collecting taxes','negotiating a treaty','organizing a campaign'],'Courts interpret the Fourteenth Amendment.','Incorporation is judicial constitutional interpretation.'),
Q('CS 14–15 • Cause and effect','Which relationship is correct?','Denial of minority rights created pressure for federal action to expand protection.',['Civil rights laws caused Jim Crow to begin.','Incorporation removed the Bill of Rights.','Jury service ended voting rights.'],'Connect injustice to reform.','Federal branches responded over time to exclusion and public pressure.'),
Q('CS 14–15 • Synthesis','Which statement best summarizes the block?','Rights depend on responsible exercise and government protection against majority abuse.',['Rights require no responsibilities or limits.','Only states protect civil rights.','Majorities may always cancel minority rights.'],'Combine responsibility and protection.','Citizens and institutions both help sustain rights.'),
Q('CS 14–15 • Application','A scenario asks how a right and responsibility connect. What should you identify?','the protected liberty and the conduct needed to respect others or the common good',['only the amendment number','the longest answer choice','the political party involved'],'Match freedom with responsible use.','The standard requires explaining the relationship.'),
Q('CS 14–15 • Application','A minority group is denied participation. What evidence best answers how government responded?','a specific amendment law executive action or court ruling that expanded access',['a private purchase','an unrelated tax change','a weather report'],'Use a branch or constitutional action.','A strong response identifies denial and the government remedy.')
];
launchMasteryGame({title:'CS 14–15 Rights and Civil Rights Comprehensive Review',subtitle:'Apply rights, responsibilities, incorporation, minority protections, and federal civil-rights actions.',assignmentKey:'gov-cs14-15-review-2026-v1',questions,linger:3800});
