// Phase II engine shared by vocabulary and review worksheets.
const GOV_SCRIPT_URL='https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec';
function launchMasteryGame(config){
 const app=document.getElementById('app'),key=config.assignmentKey+'::v1',review=/review/.test(config.assignmentKey);
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[],completed:false};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'00:00';let sec=Math.max(0,Math.floor(((S.end||new Date())-S.start)/1000));return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
 function fresh(){S.items=shuffle(config.questions).map(q=>({...q,choices:shuffle(q.choices),missed:false,mastered:false}));S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.completed=false;S.events=[]}
 function identity(){return{name:S.name,period:S.period,email:S.email}}
 function save(){if(!S.email)return;localStorage.setItem(key+'|'+S.email,JSON.stringify({...identity(),started:S.started,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),end:S.end?.toISOString(),events:S.events,completed:S.completed}))}
 function restore(mail){try{let d=JSON.parse(localStorage.getItem(key+'|'+mail)||localStorage.getItem(key));if(!d||d.email!==mail||!Array.isArray(d.items)||d.items.length!==config.questions.length)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null,end:d.end?new Date(d.end):null});return true}catch{return false}}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,...extra});S.events=S.events.slice(-500);save()}
 function post(status){if(!GOV_SCRIPT_URL)return;let first=S.items.filter(q=>q.mastered&&!q.missed).length,score=S.items.filter(q=>q.mastered).length,gameState={started:true,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),end:S.end?.toISOString(),events:S.events,completed:S.completed};fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,assignmentKey:config.assignmentKey,assignmentTitle:config.title,course:'Government',...identity(),score,total:S.items.length,percent:Math.round(first/S.items.length*100),firstAttemptScore:first,attempts:S.attempts,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',elapsed:elapsed(),events:S.events,gameState})}).catch(()=>{})}
 function timer(){clearInterval(S.timer);S.timer=setInterval(()=>{let e=document.getElementById('clock');if(e)e.textContent=elapsed()},1000)}
 function launch(){let n=document.getElementById('name').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!/^\S+@\S+\.\S+$/.test(e)){document.getElementById('status').textContent='Enter your name, period, and a valid school email.';return}S.name=n;S.period=p;S.email=e;S.started=true;if(!restore(e))fresh();log('start');post('in_progress');render();timer()}
 function resume(){let mail=document.getElementById('email').value.trim().toLowerCase();if(!mail){document.getElementById('status').textContent='Enter the same school email used when saving.';return}if(restore(mail)){render();timer();return}let status=document.getElementById('status');status.textContent='Looking for saved work…';let cb='loadGame_'+Date.now(),s=document.createElement('script');window[cb]=r=>{try{let p=r&&r.found&&r.payload;if(!p||!p.gameState){status.textContent='No saved run was found for that email.';return}let d=p.gameState;if(!Array.isArray(d.items)||d.items.length!==config.questions.length){status.textContent='Saved run uses a different question set. Start a new run.';return}Object.assign(S,d,{name:p.name||p.student?.name||'',period:p.period||p.student?.period||'',email:mail,start:new Date(d.start),end:d.end?new Date(d.end):null,started:true});save();render();timer()}finally{delete window[cb];s.remove()}};s.src=GOV_SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(config.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();s.onerror=()=>{status.textContent='Could not retrieve teacher draft.';delete window[cb];s.remove()};document.body.appendChild(s)}
 function choose(btn,value){let q=S.items[S.index];if(q.mastered)return;S.attempts++;if(value!==q.answer){q.missed=true;btn.classList.add('wrong');document.getElementById('feedback').className='feedback show hint';document.getElementById('feedback').innerHTML=`<b>Hint</b>${esc(q.hint)}`;log('incorrect',{area:q.area});post('in_progress');return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').className='feedback show good';document.getElementById('feedback').innerHTML=`<b>Correct</b>${esc(q.explain)}`;log('correct',{area:q.area,firstTry:!q.missed});post('in_progress');setTimeout(()=>{S.index++;save();render()},4000)}
 function restart(){clearInterval(S.timer);fresh();S.started=true;log('restart');post('in_progress');render();timer()}
 function finish(){if(!S.completed){S.end=new Date();S.completed=true;log('finish');post('submitted')}clearInterval(S.timer);let first=S.items.filter(q=>!q.missed).length,pct=Math.round(first/S.items.length*100);app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="result"><div class="kicker">Mastery Ticket Earned</div><h1>${esc(config.title)}</h1><p class="sub">All questions corrected. Your first attempt accuracy is preserved for your teacher.</p><div class="stats"><span class="stat">First attempt: ${first}/${S.items.length} (${pct}%)</span><span class="stat">Attempts: ${S.attempts}</span><span class="stat">Time: ${elapsed()}</span></div><div class="ticket"><h2>Completion Ticket</h2><p><b>${esc(S.name)}</b> • Period ${esc(S.period)}<br>${esc(config.title)}<br>${new Date().toLocaleString()}<br>Status: MASTERED</p></div><button class="btn" id="restart">Restart Assignment</button></section>`;document.getElementById('restart').onclick=restart}
 function render(){if(!S.started){app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="hero"><div class="kicker">Legend Mastery Series • American Government</div><h1>${esc(config.title)}</h1><p class="sub">${esc(config.subtitle)}</p><div class="pills"><span class="pill">${config.questions.length} questions</span><span class="pill">Hint after a miss</span><span class="pill">Corrections allowed</span><span class="pill">First attempt recorded</span></div></section><section class="panel"><div class="identity"><label>Name<input id="name" autocomplete="name"></label><label>Period<select id="period"><option value="">Choose…</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><button class="btn" id="start">Start / Continue</button> <button class="btn secondary" id="resume">Retrieve Saved Run</button><div class="status" id="status"></div></section>`;document.getElementById('start').onclick=launch;document.getElementById('resume').onclick=resume;return}if(S.index>=S.items.length){finish();return}let q=S.items[S.index],first=S.items.slice(0,S.index).filter(x=>!x.missed).length,acc=S.index?Math.round(first/S.index*100):100;app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="question"><div class="topline"><div><div class="area">${esc(q.area)}</div><b>Question ${S.index+1} of ${S.items.length}</b></div><div class="stats"><span class="stat">First try ${acc}%</span><span class="stat" id="clock">${elapsed()}</span></div></div><div class="progress"><div style="width:${S.index/S.items.length*100}%"></div></div><div class="stem">${esc(q.stem)}</div><div class="choices">${q.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="feedback" class="feedback"></div><button class="btn secondary" id="reset">Reset Assignment</button></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value));document.getElementById('reset').onclick=()=>{if(confirm('Restart this assignment at Question 1? Earlier teacher records remain in the spreadsheet.'))restart()}}
 render();window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(S.started&&!S.completed)log(document.hidden?'tab_leave':'tab_return')});document.addEventListener('copy',()=>S.started&&!S.completed&&log('copy'));document.addEventListener('paste',()=>S.started&&!S.completed&&log('paste'));
}

const terms=[["separation of powers","dividing government authority among legislative executive and judicial branches"],["checks and balances","powers allowing each branch to limit the others"],["limited government","government restricted by constitutions and laws"],["popular sovereignty","government authority begins with the people"],["bill of rights","a list of protected individual liberties"],["initiative","a process allowing Ohio citizens to propose a law or constitutional amendment"],["referendum","a vote allowing Ohio citizens to approve or reject a law"],["elected judges","Ohio judges chosen by voters"],["appointed federal judges","federal judges nominated by the president and confirmed by the Senate"],["legislative term limits","limits on how long Ohio legislators may serve consecutively"],["1851 Ohio Constitution","Ohio constitution that expanded elected offices and limited state debt"],["district courts","courts created by the 1851 Ohio Constitution"],["state taxes","revenue citizens pay to support Ohio government services"],["Ohio National Guard","state-based military force citizens may join"],["petition for ballot access","citizen signatures used to place an issue or candidate before voters"],["civic activity","organized citizen action addressing a community need"],["local public office","an elected or appointed position in local government"],["public meeting","a board or commission meeting citizens may attend"],["community watch","neighbors cooperating to improve local safety"],["volunteer fire department","local emergency service supported by trained volunteers"],["state government","government acting across Ohio"],["local government","county city village township or school-district government"],["candidate","a person seeking public office"],["informed voting","researching issues and candidates before casting a ballot"],["constitutional comparison","identifying similarities and differences between governing documents"]];
const questions=terms.map((t,i)=>({area:i<Math.ceil(terms.length/2)?'CS 16':'CS 17',stem:`Which definition best matches ${t[0]}?`,answer:t[1],choices:[t[1],terms[(i+7)%terms.length][1],terms[(i+13)%terms.length][1],terms[(i+19)%terms.length][1]],hint:`Think about how ${t[0]} is used in this unit.`,explain:`${t[0]} means ${t[1]}.`}));
// Plausible, similarly sized distractors drawn from this block's actual terms.
questions.forEach((q,i)=>{let pool=questions.filter((x,j)=>j!==i&&x.answer!==q.answer).sort((a,b)=>Math.abs(a.answer.length-q.answer.length)-Math.abs(b.answer.length-q.answer.length));let picked=[];for(let j of [i%pool.length,(i+7)%pool.length,(i+13)%pool.length])if(pool[j]&&!picked.includes(pool[j].answer))picked.push(pool[j].answer);for(let x of pool)if(picked.length<3&&!picked.includes(x.answer))picked.push(x.answer);q.choices=[q.answer,...picked.slice(0,3)]});
// Plausible, similarly sized distractors drawn from this block's actual terms.
questions.forEach((q,i)=>{let pool=questions.filter((x,j)=>j!==i&&x.answer!==q.answer).sort((a,b)=>Math.abs(a.answer.length-q.answer.length)-Math.abs(b.answer.length-q.answer.length));let picked=[];for(let j of [i%pool.length,(i+7)%pool.length,(i+13)%pool.length])if(pool[j]&&!picked.includes(pool[j].answer))picked.push(pool[j].answer);for(let x of pool)if(picked.length<3&&!picked.includes(x.answer))picked.push(x.answer);q.choices=[q.answer,...picked.slice(0,3)]});
launchMasteryGame({title:"CS 16–17 Ohio Government and Citizenship Vocabulary",subtitle:"Compare the Ohio and U.S. Constitutions and examine how citizens assist state and local government.",assignmentKey:"gov-cs16-17-vocabulary-2026-v1",questions,linger:3200});
