const GOV_SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
function launchMasteryGame(config){
 const app=document.getElementById('app'),key=config.assignmentKey+'::v1';
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[]};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'00:00';const sec=Math.floor(((S.end||new Date())-S.start)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
 function fresh(){S.items=shuffle(config.questions).map(q=>({...q,choices:shuffle(q.choices),missed:false,mastered:false}));S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.events=[]}
 function identity(){return{name:S.name,period:S.period,email:S.email}}
 function save(){localStorage.setItem(key,JSON.stringify({...identity(),started:S.started,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events}))}
 function restore(){try{const d=JSON.parse(localStorage.getItem(key));if(!d)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null});return true}catch{return false}}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,...extra});save()}
 function post(status){if(!GOV_SCRIPT_URL)return;const first=S.items.filter(q=>q.mastered&&!q.missed).length,pct=Math.round(first/S.items.length*100),gameState={started:true,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events};fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,assignmentKey:config.assignmentKey,assignmentTitle:config.title,...identity(),score:first,total:S.items.length,percent:pct,attempts:S.attempts,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',elapsed:elapsed(),events:S.events,gameState})}).catch(()=>{})}
 function launch(){const n=document.getElementById('name').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!e){document.getElementById('status').textContent='Enter your name, period, and school email.';return}S.name=n;S.period=p;S.email=e;S.started=true;fresh();log('start');post('in_progress');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function resume(){const mail=document.getElementById('email').value.trim().toLowerCase();if(!mail){document.getElementById('status').textContent='Enter the same school email used when saving.';return}if(restore()&&S.started&&S.email===mail){render();startTimer();return}const status=document.getElementById('status');status.textContent='Looking for saved work…';const cb='loadGame_'+Date.now();window[cb]=r=>{try{const p=r&&r.found&&r.payload;if(!p||!p.gameState){status.textContent='No saved run was found for that email.';return}Object.assign(S,p.gameState,{name:p.name||'',period:p.period||'',email:p.email||mail,start:new Date(p.gameState.start),started:true});save();render();startTimer()}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=GOV_SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(config.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();s.onerror=()=>status.textContent='Cloud retrieval was blocked. No local run was found.';document.body.appendChild(s)}
 function startTimer(){if(S.timer)clearInterval(S.timer);S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function choose(btn,value){const q=S.items[S.index];if(q.mastered)return;S.attempts++;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('wrong'));if(value!==q.answer){q.missed=true;btn.classList.add('wrong');document.getElementById('feedback').className='feedback show hint';document.getElementById('feedback').innerHTML=`<b>Hint</b>${esc(q.hint)}`;log('incorrect',{area:q.area});return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').className='feedback show good';document.getElementById('feedback').innerHTML=`<b>Correct</b>${esc(q.explain)}`;log('correct',{area:q.area,firstTry:!q.missed});post('in_progress');setTimeout(()=>{S.index++;save();render()},config.linger||3500)}
 function restart(){if(S.timer)clearInterval(S.timer);fresh();log('restart');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function finish(){if(S.timer)clearInterval(S.timer);S.end=new Date();const first=S.items.filter(q=>!q.missed).length,perfect=first===S.items.length,pct=Math.round(first/S.items.length*100);log('finish',{perfect});post(perfect?'submitted':'needs_retry');localStorage.setItem(key,JSON.stringify({...S,end:S.end.toISOString(),start:S.start.toISOString()}));app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="result"><div class="kicker">${perfect?'Mastery Ticket Earned':'Review Complete • Ticket Locked'}</div><h1>${esc(config.title)}</h1><p class="sub">${perfect?'Perfect first-try mastery. Show this ticket to your teacher.':'You corrected every item, but a perfect first-try run is required. Review the missed areas and restart.'}</p><div class="stats"><span class="stat">Accuracy: ${pct}%</span><span class="stat">First try: ${first}/${S.items.length}</span><span class="stat">Attempts: ${S.attempts}</span><span class="stat">Time: ${elapsed()}</span></div><div class="ticket ${perfect?'':'locked'}"><h2>${perfect?'Completion Ticket':'Ticket Locked'}</h2><p><b>${esc(S.name)}</b> • Period ${esc(S.period)}<br>${esc(config.title)}<br>${new Date().toLocaleString()}<br>${perfect?'Status: 100% PERFECT RUN':'Restart required'}</p></div><button class="btn" id="restart">Restart Full Game</button></section>`;document.getElementById('restart').onclick=restart}
 function render(){if(!S.started){app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="hero"><div class="kicker">Legend Mastery Series • American Government</div><h1>${esc(config.title)}</h1><p class="sub">${esc(config.subtitle)}</p><div class="pills"><span class="pill">${config.questions.length} questions</span><span class="pill">Hint after a miss</span><span class="pill">Auto-check</span><span class="pill">100% run required</span></div></section><section class="panel"><div class="identity"><label>Name<input id="name" autocomplete="name"></label><label>Period<select id="period"><option value="">Choose…</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><button class="btn" id="start">Start Assignment</button> <button class="btn secondary" id="resume">Retrieve Saved Run</button><div class="status" id="status"></div></section>`;document.getElementById('start').onclick=launch;document.getElementById('resume').onclick=resume;return}if(S.index>=S.items.length){finish();return}const q=S.items[S.index],first=S.items.slice(0,S.index).filter(x=>!x.missed).length,acc=S.index?Math.round(first/S.index*100):100;app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="question"><div class="topline"><div><div class="area">${esc(q.area)}</div><b>Question ${S.index+1} of ${S.items.length}</b></div><div class="stats"><span class="stat">Accuracy ${acc}%</span><span class="stat" id="clock">${elapsed()}</span></div></div><div class="progress"><div style="width:${S.index/S.items.length*100}%"></div></div><div class="stem">${esc(q.stem)}</div><div class="choices">${q.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="feedback" class="feedback"></div></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value))}
 render();window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(S.started)log(document.hidden?'tab_leave':'tab_return')});document.addEventListener('copy',()=>S.started&&log('copy'));document.addEventListener('paste',()=>S.started&&log('paste'));
}
const terms=[["fiscal policy","government decisions about taxing and spending"],["taxation","government collection of required revenue"],["government spending","public money used for programs goods and services"],["economic growth","increase in production income and economic activity"],["expansionary fiscal policy","increased spending or reduced taxes intended to encourage growth"],["contractionary fiscal policy","reduced spending or increased taxes intended to slow growth"],["budget deficit","government spending exceeding revenue"],["budget surplus","government revenue exceeding spending"],["public debt","total accumulated government borrowing"],["regulation","government rule directing or limiting economic activity"],["consumer protection","rules shielding buyers from unsafe deceptive or unfair practices"],["unfair business practice","deceptive anticompetitive or abusive market conduct"],["compliance cost","expense a business incurs to follow regulations"],["corporate profit","business revenue remaining after costs"],["monetary policy","Federal Reserve actions affecting money and credit"],["Federal Reserve","central bank of the United States"],["money supply","amount of money available in the economy"],["interest rate","cost of borrowing money"],["reserve requirement","share of deposits banks must hold rather than lend"],["open-market operations","Federal Reserve purchases and sales of government securities"],["bond purchase","Fed action adding money to banks and encouraging growth"],["bond sale","Fed action removing money from banks and slowing growth"],["expansionary monetary policy","lower rates bond purchases or lower reserves to encourage growth"],["contractionary monetary policy","higher rates bond sales or higher reserves to slow growth"],["inflation","general rise in prices over time"]];
const questions=terms.map((t,i)=>({area:i<Math.ceil(terms.length/2)?'CS 20':'CS 21',stem:`Which definition best matches ${t[0]}?`,answer:t[1],choices:[t[1],terms[(i+7)%terms.length][1],terms[(i+13)%terms.length][1],terms[(i+19)%terms.length][1]],hint:`Think about how ${t[0]} is used in this unit.`,explain:`${t[0]} means ${t[1]}.`}));
launchMasteryGame({title:"CS 20–21 Fiscal and Monetary Policy Vocabulary",subtitle:"Distinguish fiscal, regulatory, and monetary tools and predict their effects on economic growth.",assignmentKey:"gov-cs20-21-vocabulary-2026-v1",questions,linger:3200});
