const ARCHIVES_AMENDMENTS='https://www.archives.gov/founding-docs/amendments-11-27';
const ARCHIVES_14='https://www.archives.gov/milestone-documents/14th-amendment';
const ARCHIVES_EC='https://www.archives.gov/electoral-college/about';
const Q=(area,stem,answer,wrong,hint,explain)=>{
  const source=area.includes('Electoral College')||area.includes('Federalism')?ARCHIVES_EC:
    area.includes('Fourteenth')||area.includes('Incorporation')?ARCHIVES_14:ARCHIVES_AMENDMENTS;
  return {area,stem,answer,choices:[answer,...wrong],hint,explain,source,where:hint};
};
const questions=[
Q('CS 9 • Thirteenth Amendment','A state attempts to legally restore slavery. Which amendment most directly prohibits this action?','Thirteenth Amendment',['Fourteenth Amendment','Nineteenth Amendment','Twenty-second Amendment'],'Think abolition.','The Thirteenth Amendment abolished slavery and involuntary servitude, except as criminal punishment.'),
Q('CS 9 • Fourteenth Amendment','A child is born in Ohio to parents who are not U.S. citizens. Which amendment establishes the child’s U.S. citizenship?','Fourteenth Amendment',['Thirteenth Amendment','Fifteenth Amendment','Twenty-sixth Amendment'],'Think birthright citizenship.','The Citizenship Clause recognizes persons born in the United States as citizens.'),
Q('CS 9 • Fourteenth Amendment','A state takes a person’s property without notice or a fair hearing. Which protection is most directly involved?','Fourteenth Amendment due process',['Fifteenth Amendment voting protection','Nineteenth Amendment suffrage','Twenty-second Amendment term limits'],'The state skipped fair procedures.','The Fourteenth Amendment prohibits states from depriving life, liberty, or property without due process.'),
Q('CS 9 • Fourteenth Amendment','A state law gives legal protection to one racial group but denies it to another. Which clause is most directly involved?','Equal Protection Clause',['Supremacy Clause','Necessary and Proper Clause','Establishment Clause'],'Think equal treatment under state law.','The Fourteenth Amendment requires states to provide equal protection to all persons.'),
Q('CS 9 • Fourteenth Amendment / Incorporation','A state government violates a protection in the Bill of Rights that has been applied to the states. Which constitutional principle allows that protection to be enforced against the state?','Incorporation through the Fourteenth Amendment',['Reserved powers under the Tenth Amendment','Supremacy through the Necessary and Proper Clause','Presidential succession under the Twenty-fifth Amendment'],'Think about how Bill of Rights protections came to apply to state governments.','Through incorporation, many Bill of Rights protections have been applied to the states through the Fourteenth Amendment.'),
Q('CS 9 • Fifteenth Amendment','A state refuses to register citizens because of their race. Which amendment is most directly violated?','Fifteenth Amendment',['Thirteenth Amendment','Nineteenth Amendment','Twenty-third Amendment'],'Think race and voting.','The Fifteenth Amendment forbids denial of voting rights based on race, color, or previous servitude.'),
Q('CS 9 • Reconstruction','Which three amendments are collectively called the Reconstruction Amendments?','Thirteenth, Fourteenth, and Fifteenth',['First, Second, and Third','Nineteenth, Twenty-fourth, and Twenty-sixth','Twelfth, Twenty-second, and Twenty-fifth'],'They were adopted after the Civil War.','Amendments 13–15 ended slavery and added citizenship, equality, and voting protections.'),
Q('CS 9 • Reconstruction','Which sequence correctly describes the Reconstruction Amendments?','end slavery → citizenship → voting by race',['protect speech → bear arms → ban searches','women’s suffrage → ban poll taxes → voting age 18','separate ballots → D.C. electors → succession'],'Follow Amendments 13, 14, and 15 in order.','The amendments moved from freedom, to citizenship/equality, to political participation.'),
Q('CS 9 • Continued struggle','Why did the Reconstruction Amendments not produce immediate equality?','Jim Crow laws and unequal enforcement persisted.',['The amendments applied only to federal officials, not state laws.','The amendments permanently ended all racial discrimination.','State governments could legally restore slavery under the amendments.'],'Constitutional text did not erase resistance and discriminatory enforcement.','Jim Crow and other practices undermined constitutional protections for generations.'),
Q('CS 9 • Jim Crow','A state requires racially separate public facilities. Which historical system does this represent?','Jim Crow segregation',['the Electoral College','presidential succession','birthright citizenship'],'Think enforced racial separation after Reconstruction.','Jim Crow laws enforced segregation despite the Fourteenth Amendment.'),
Q('CS 9 • Analysis','Which conclusion is best supported by the history of Reconstruction and Jim Crow?','Constitutional rights often require enforcement.',['Constitutional amendments automatically change every local practice.','Voting rights alone immediately ended segregation nationwide.','States always implemented new constitutional protections without opposition.'],'Compare the legal changes with what happened afterward.','The gap between constitutional promise and lived equality persisted.'),
Q('CS 10 • Fifteenth Amendment','Which voting-rights amendment prohibits racial discrimination in voting?','Fifteenth Amendment',['Nineteenth Amendment','Twenty-fourth Amendment','Twenty-sixth Amendment'],'This amendment was part of Reconstruction.','The Fifteenth Amendment protects voting regardless of race, color, or previous servitude.'),
Q('CS 10 • Nineteenth Amendment','A state refuses to let women vote solely because they are women. Which amendment applies?','Nineteenth Amendment',['Fifteenth Amendment','Twenty-fourth Amendment','Twenty-sixth Amendment'],'Think women’s suffrage.','The Nineteenth Amendment prohibits denying voting rights based on sex.'),
Q('CS 10 • Twenty-fourth Amendment','A citizen is told to pay a fee before voting in a federal election. Which amendment applies?','Twenty-fourth Amendment',['Twenty-second Amendment','Nineteenth Amendment','Twenty-sixth Amendment'],'The fee is a poll tax.','The Twenty-fourth Amendment prohibits poll taxes in federal elections.'),
Q('CS 10 • Twenty-sixth Amendment','A state sets the voting age at 21 and refuses to register a 19-year-old citizen. Which amendment applies?','Twenty-sixth Amendment',['Nineteenth Amendment','Twenty-fourth Amendment','Twenty-second Amendment'],'Think voting age 18.','The Twenty-sixth Amendment protects voting rights for citizens 18 and older.'),
Q('CS 10 • Poll taxes','Why did poll taxes disenfranchise many poor citizens?','Poll taxes made voting unaffordable.',['A property requirement kept people from registering.','A literacy test excluded people unable to pass it.','An age restriction prevented citizens under 21 from voting.'],'Focus on the financial barrier.','Poll taxes conditioned voting on payment and were used to suppress African American voters.'),
Q('CS 10 • Suffrage','Which set contains only suffrage-expanding amendments emphasized in CS 10?','15th, 19th, 24th, and 26th',['13th, 14th, 22nd, and 25th','1st, 2nd, 4th, and 10th','12th, 22nd, 23rd, and 25th'],'Think race, sex, poll tax, and age.','CS 10 emphasizes four amendments that removed voting barriers.'),
Q('CS 10 • Cause and effect','Which cause-and-effect relationship is correct?','Poll taxes limited voting; the 24th banned them in federal elections.',['The 19th restricted women’s votes; the 15th reversed that restriction.','The 26th increased the voting age; the 24th lowered it again.','The 15th created poll taxes; the 19th eliminated those taxes.'],'Match a barrier with the amendment addressing it.','The Twenty-fourth Amendment removed a financial barrier to federal voting.'),
Q('CS 10 • Comparison','How are the Fifteenth and Nineteenth Amendments similar?','Both protect voting rights.',['Both regulate the way electoral votes are cast and counted.','Both establish constitutional rules for presidential succession.','Both restrict how many terms an elected president may serve.'],'One concerns race; the other concerns sex.','Both extended suffrage by prohibiting a form of discrimination.'),
Q('CS 10 • Application','Which amendment most directly expanded the electorate during the Vietnam era?','Twenty-sixth Amendment',['Thirteenth Amendment','Twenty-second Amendment','Twenty-third Amendment'],'“Old enough to fight, old enough to vote.”','The Twenty-sixth Amendment lowered the voting age to 18.'),
Q('CS 11 • Electoral College','How is a state’s number of electoral votes determined?','House seats plus two senators',['its share of the national population plus its governor','its total number of state legislators and federal judges','its counties plus its representatives in the U.S. Senate'],'Combine House and Senate representation.','Each state receives electors equal to its total congressional delegation.'),
Q('CS 11 • Electoral College','What must a presidential candidate normally win to secure the presidency?','more than half of electoral votes',['a plurality of the national popular vote','a majority of votes in every individual state','a two-thirds vote in the House of Representatives'],'More than half is required.','The Electoral College requires a majority of appointed electoral votes.'),
Q('CS 11 • Electoral College','No presidential candidate receives a majority of electoral votes. What happens next under the Constitution?','The House chooses among the top three electoral candidates.',['The Senate chooses from the top three presidential candidates.','The Supreme Court chooses the national popular-vote winner.','The incumbent president stays until a new national election.'],'Think about a contingent election after no Electoral College majority.','Under the Twelfth Amendment, the House chooses the president from the top three electoral-vote recipients, with each state delegation casting one vote.'),
Q('CS 11 • Federalism','Why does the Electoral College reflect federalism?','Electoral votes are assigned by state.',['Federal judges are assigned electoral votes according to state population.','County governments choose the president through separate local ballots.','Congress appoints every elector without involving individual states.'],'Think national selection through state units.','The system combines a national office with state-based electoral votes.'),
Q('CS 11 • Twelfth Amendment','Electors cast separate ballots for president and vice president. Which amendment created this procedure?','Twelfth Amendment',['Twenty-second Amendment','Twenty-third Amendment','Twenty-fifth Amendment'],'Think separate ballots.','The Twelfth Amendment revised Electoral College voting after early tie problems.'),
Q('CS 11 • Twelfth Amendment','What problem was the Twelfth Amendment designed to reduce?','Confusion from combined ballots',['The absence of electoral votes for Washington, D.C., residents','The possibility of a president serving more than two elected terms','The lack of a constitutional process for presidential disability'],'The original process did not separate the two offices on ballots.','Separate ballots clarified selection for president and vice president.'),
Q('CS 11 • Twenty-second Amendment','A president wins election twice and seeks a third elected term. Which amendment limits this?','Twenty-second Amendment',['Twenty-fourth Amendment','Twenty-third Amendment','Twenty-fifth Amendment'],'Think presidential term limits.','The Twenty-second Amendment generally limits a president to two elected terms.'),
Q('CS 11 • Twenty-second Amendment / Cause and effect','Which historical development most directly helped lead to adoption of the Twenty-second Amendment?','Franklin D. Roosevelt was elected president four times.',['Congress repeatedly removed presidents through impeachment.','Washington, D.C., gained votes in the Electoral College.','Electors stopped casting separate ballots for president and vice president.'],'Think about the presidential tradition that changed during Franklin Roosevelt’s presidency.','After Franklin D. Roosevelt was elected four times, the Twenty-second Amendment established constitutional limits on presidential tenure.'),
Q('CS 11 • Twenty-third Amendment','Residents of Washington, D.C., participate in a presidential election through electors. Which amendment made this possible?','Twenty-third Amendment',['Twelfth Amendment','Twenty-second Amendment','Twenty-fifth Amendment'],'Think the District of Columbia.','The Twenty-third Amendment granted D.C. electoral votes.'),
Q('CS 11 • Twenty-fifth Amendment','The president resigns and the vice president becomes president. Which amendment clarifies this succession?','Twenty-fifth Amendment',['Twelfth Amendment','Twenty-second Amendment','Twenty-third Amendment'],'Think vacancy and succession.','The Twenty-fifth Amendment confirms vice-presidential succession to the presidency.'),
Q('CS 11 • Twenty-fifth Amendment','The president temporarily cannot perform official duties during a medical procedure. Which amendment provides a transfer process?','Twenty-fifth Amendment',['Fourteenth Amendment','Twenty-second Amendment','Twenty-fourth Amendment'],'Think presidential inability.','The Twenty-fifth Amendment addresses temporary presidential disability.'),
Q('CS 11 • Twenty-fifth Amendment','Which situation specifically calls for a Twenty-fifth Amendment disability procedure rather than ordinary succession after a presidential vacancy?','The president remains in office but cannot temporarily serve.',['The president resigns, creating a permanent vacancy in the office.','The president finishes two elected terms and cannot run again.','No candidate earns an Electoral College majority in the election.'],'The key distinction is that the president is still in office but unable to serve temporarily.','The Twenty-fifth Amendment provides procedures for transferring presidential powers when a president is unable to discharge the duties of the office.'),
Q('CS 11 • Twenty-fifth Amendment','The vice presidency becomes vacant. What process does the Twenty-fifth Amendment provide?','The president nominates; both chambers confirm.',['The Supreme Court appoints a new vice president by majority vote.','State governors elect a vice president in a special convention.','The House speaker assumes the vice presidency without confirmation.'],'Think nomination plus congressional confirmation.','Section 2 provides a method to fill a vice-presidential vacancy.'),
Q('CS 11 • Comparison','Which pairing is correct?','22nd: term limits; 25th: succession',['12th—D.C. electors; 23rd—separate presidential ballots','19th—poll taxes; 24th—women’s voting rights','13th—equal protection; 14th—abolition of slavery'],'Match each amendment to its precise change.','The Twenty-second limits tenure; the Twenty-fifth maintains continuity of presidential power.'),
Q('CS 11 • Sequence','Which sequence correctly orders presidential amendments by number?','12th ballots → 22nd terms → 23rd D.C. votes → 25th succession',['12th—term limits; 22nd—separate ballots; 23rd—disability; 25th—D.C. electors','12th—D.C. electors; 22nd—disability; 23rd—term limits; 25th—ballots','12th—succession; 22nd—D.C. electors; 23rd—ballots; 25th—term limits'],'Use the four amendment-number associations.','The sequence accurately pairs Amendments 12, 22, 23, and 25.'),
Q('Mixed • Amendment identification','A question mentions citizenship, due process, and equal protection. Which amendment should you identify first?','Fourteenth Amendment',['Fifteenth Amendment','Nineteenth Amendment','Twenty-fifth Amendment'],'These three protections appear together.','The Fourteenth Amendment contains all three concepts.'),
Q('Mixed • Amendment identification','A question mentions separate presidential and vice-presidential electoral ballots. Which amendment should you identify?','Twelfth Amendment',['Twenty-second Amendment','Twenty-third Amendment','Twenty-fifth Amendment'],'Separate ballots is the anchor phrase.','The Twelfth Amendment changed Electoral College balloting.'),
Q('Mixed • Analysis','Which statement best connects CS 9 and CS 10?','Reconstruction rights preceded later voting expansions.',['Reconstruction set presidential term limits; later amendments ended them.','Reconstruction established the Electoral College; later amendments abolished it.','Reconstruction guaranteed equal voting access; later amendments restricted it.'],'Think expanding constitutional inclusion over time.','CS 9 establishes postwar protections; CS 10 traces continued suffrage expansion.'),
Q('Mixed • Analysis','Which statement best connects CS 10 and CS 11?','Both change voting or presidential rules.',['Both abolished slavery and established citizenship through new amendments.','Both created equal protection requirements for state criminal trials.','Both replaced state elections with direct national presidential elections.'],'Compare who may participate with how presidential government operates.','CS 10 concerns access to voting; CS 11 concerns Electoral College and presidential procedures.'),
Q('CS 9–11 • Synthesis','What is the broad story of CS 9–11?','Amendments expanded rights and presidential rules.',['Amendments reduced voting access and removed citizenship protections.','Amendments ended federalism and replaced the Constitution with state law.','Amendments eliminated the Electoral College and presidential succession.'],'Combine civil rights, voting rights, and presidential government.','These content statements show constitutional change affecting both individual participation and federal structure.')
];
launchMasteryGame({title:'CS 9–11 Comprehensive Review',subtitle:'Apply Reconstruction protections, suffrage amendments, Electoral College rules, and presidential amendments in short scenarios.',assignmentKey:'gov-cs9-11-review-2026-v1',questions,linger:3800});