const GOV_SCRIPT_URL='https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec';
function launchMasteryGame(config){
 const app=document.getElementById('app'),key=config.assignmentKey+'::v1';
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[],completed:false};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'0:00';let x=Math.max(0,Math.floor(((S.end||new Date())-S.start)/1000));return`${Math.floor(x/60)}:${String(x%60).padStart(2,'0')}`};
 const firstScore=()=>S.items.filter(q=>q.mastered&&!q.missed).length;
 function fresh(){S.items=shuffle(config.questions).map(q=>({...q,choices:shuffle(q.choices),missed:false,mastered:false}));S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.completed=false;S.events=[]}
 function save(){if(S.email)localStorage.setItem(key+'|'+S.email,JSON.stringify({...S,start:S.start?.toISOString(),end:S.end?.toISOString(),timer:null}))}
 function restore(mail){try{const d=JSON.parse(localStorage.getItem(key+'|'+mail)||'null');if(!d||d.email!==mail||!Array.isArray(d.items)||d.items.length!==config.questions.length)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null,end:d.end?new Date(d.end):null,timer:null});return true}catch{return false}}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,...extra});S.events=S.events.slice(-500);save()}
 function post(status){if(!GOV_SCRIPT_URL||!S.email)return;const data={action:'save',status,assignmentKey:config.assignmentKey,assignmentTitle:config.title,course:'Government',name:S.name,period:S.period,email:S.email,score:S.items.filter(q=>q.mastered).length,total:S.items.length,percent:Math.round(firstScore()/S.items.length*100),firstAttemptScore:firstScore(),attempts:S.attempts,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',elapsed:elapsed(),events:S.events,gameState:{started:true,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),end:S.end?.toISOString(),events:S.events,completed:S.completed}};fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(data)}).catch(()=>{})}
 function timer(){clearInterval(S.timer);S.timer=setInterval(()=>{const e=document.getElementById('runtimeStat');if(e)e.textContent=elapsed()},1000)}
 function start(){const n=document.getElementById('studentName').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!/^\S+@\S+\.\S+$/.test(e)){document.getElementById('saveStatus').textContent='Enter full name, period, and a valid school email first.';return}S.name=n;S.period=p;S.email=e;S.started=true;if(!restore(e))fresh();log('start');post('in_progress');render();timer()}
 function resume(){const e=document.getElementById('email').value.trim().toLowerCase();if(!e){document.getElementById('saveStatus').textContent='Enter the same school email used when saving.';return}if(restore(e)){S.started=true;render();timer();return}document.getElementById('saveStatus').textContent='No saved run was found on this device.'}
 function choose(btn,value){const q=S.items[S.index];if(q.mastered)return;S.attempts++;if(value!==q.answer){q.missed=true;btn.classList.add('wrong');const f=document.getElementById('feedback');f.className='feedback bad';f.innerHTML=`<strong>Not yet.</strong> ${esc(q.hint)}`;log('incorrect',{area:q.area});post('in_progress');return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);const f=document.getElementById('feedback');f.className='feedback good';f.innerHTML=`<strong>Correct.</strong> ${esc(q.explain)}<span class="advance-note">Advancing to the next question…</span>`;log('correct',{area:q.area,firstTry:!q.missed});post('in_progress');setTimeout(()=>{S.index++;save();render()},4000)}
 function restart(){clearInterval(S.timer);fresh();S.started=true;log('restart');post('in_progress');render();timer()}
 function shell(inner){return`<p><a class="back" href="../../">← Back to Government Hub</a></p>${inner}`}
 function header(){return`<header class="hero"><div><div class="eyebrow">LEGEND MASTERY SERIES • AMERICAN GOVERNMENT</div><h1>${esc(config.title)}</h1><p>${esc(config.subtitle)}</p><p>Your <strong>first response is recorded for this run’s score</strong>. Then use hints and corrections until every question is mastered.</p></div><div class="feature-pills"><span>First Attempt Preserved ✓</span><span>Corrections to Mastery ✓</span><span>Hints After Misses ✓</span><span>Saved Progress ✓</span></div></header>`}
 function finish(){if(!S.completed){S.end=new Date();S.completed=true;log('finish');post('submitted')}clearInterval(S.timer);app.innerHTML=shell(header()+`<section class="completion"><div class="section-label">COMPLETION TICKET</div><h2>Assignment mastery complete</h2><h3>Completed by: ${esc(S.name)} • Period ${esc(S.period)}</h3><p>Mastery complete: ${S.items.length}/${S.items.length} corrected • First-attempt score: ${firstScore()}/${S.items.length} • ${S.attempts} total attempts • ${elapsed()} runtime.</p><button id="restart">Restart from Question 1</button></section>`);document.getElementById('restart').onclick=restart}
 function render(){
  if(!S.started){app.innerHTML=shell(header()+`<section class="student-panel"><div><div class="section-label">STUDENT INFORMATION</div><h2>Your information and save controls</h2><p>Your school email connects this browser to your saved progress.</p></div><div class="fields"><label>Full name<input id="studentName" autocomplete="name"></label><label>Class period<select id="period"><option value="">Choose</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><div class="actions"><button id="startBtn">Start / Continue</button><button id="loadBtn" class="secondary">Load previous work</button><button id="resetBtn" class="secondary">Reset Assignment</button></div><p id="saveStatus" class="status"></p></section>`);document.getElementById('startBtn').onclick=start;document.getElementById('loadBtn').onclick=resume;document.getElementById('resetBtn').onclick=()=>{if(confirm('Start this assignment over?')){const e=document.getElementById('email').value.trim().toLowerCase();if(e)localStorage.removeItem(key+'|'+e);document.getElementById('saveStatus').textContent='Saved run cleared on this device.'}};return}
  if(S.index>=S.items.length){finish();return}
  const q=S.items[S.index],answered=S.index,first=S.items.slice(0,S.index).filter(x=>!x.missed).length;
  app.innerHTML=shell(header()+`<section class="student-panel compact"><div><div class="section-label">STUDENT INFORMATION</div><h2>Your information and save controls</h2><p>${esc(S.name)} • Period ${esc(S.period)} • ${esc(S.email)}</p></div><div class="actions"><button class="secondary" id="resetBtn">Reset Assignment</button></div></section><div class="workspace"><section class="question-panel"><div class="section-label">QUESTION</div><div class="stats"><div><strong>${S.index+1} / ${S.items.length}</strong><span>Progress</span></div><div><strong>${first} / ${answered}</strong><span>First-Attempt Score</span></div><div><strong id="runtimeStat">${elapsed()}</strong><span>Runtime</span></div></div><div class="question-card"><h2>${esc(q.area)} • Question ${S.index+1}</h2><p class="prompt">${esc(q.stem)}</p><div class="choices">${q.choices.map((c,i)=>`<button class="choice" data-value="${esc(c)}"><span class="choice-letter">${'ABCD'[i]}.</span><span>${esc(c)}</span></button>`).join('')}</div><div id="feedback" class="feedback"></div><div class="source-box"><a href="${esc(q.source)}" target="_blank" rel="noopener">Open supporting source ↗</a><p><strong>Where to look:</strong> ${esc(q.where)}</p></div></div></section><aside class="side-panel"><div class="section-label">RULES</div><ul><li><strong>First attempt:</strong> Your first answer becomes your score for that question.</li><li><strong>Mastery:</strong> If you miss, use the hint and source to correct it.</li><li>A correct answer shows an explanation for four seconds before advancing.</li></ul><div class="side-section"><div class="section-label">WHAT THIS PRACTICES</div><p>Reconstruction Amendments, suffrage expansion, Electoral College rules, presidential amendments, and constitutional change.</p></div><div class="side-section"><div class="section-label">SAVED PROGRESS</div><p>Progress saves in this browser and is sent to your teacher spreadsheet.</p></div></aside></div>`);
  document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value));document.getElementById('resetBtn').onclick=()=>{if(confirm('Restart this assignment at Question 1? Earlier teacher records remain in the spreadsheet.'))restart()}
 }
 render();window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(S.started&&!S.completed)log(document.hidden?'tab_leave':'tab_return')});document.addEventListener('copy',()=>S.started&&!S.completed&&log('copy'));document.addEventListener('paste',()=>S.started&&!S.completed&&log('paste'));
}