(function(){
window.BLOCK_CONFIG={assignmentKey:"gov-cs8-vocabulary-2026-v2",title:"CS 8 Bill of Rights Vocabulary",description:"Master the essential language of civil liberties and constitutional protections.",practice:"Identify and distinguish vocabulary from the First, Second, Fourth, Fifth, Sixth, Eighth, and Tenth Amendments."};
const raw=[
["v01","Foundations","Which definition best matches Bill of Rights?",["the first ten amendments protecting liberties and limiting federal power","the seven articles establishing the original structure of the national government","the collection of state constitutions written before independence from Britain","the opening section explaining the general purposes of the Constitution"],"Think about Amendments 1–10.","The Bill of Rights is the first ten amendments and protects liberties against government action."],
["v02","Foundations","Which definition best matches civil liberties?",["fundamental freedoms protected from improper government interference","benefits that government provides only to citizens who hold public office","responsibilities that states must transfer permanently to the federal government","procedures used by political parties to select candidates for national elections"],"Think of freedoms government ordinarily may not violate.","Civil liberties are fundamental freedoms protected from improper government interference."],
["v03","First Amendment","Which definition best matches freedom of speech?",["the right to express ideas and opinions without improper government restriction","the authority to refuse every law with which a person personally disagrees","the ability to enter any private property without permission to deliver a political message","the power to prevent other people from expressing an opposing opinion"],"Focus on expression of ideas and opinions.","Freedom of speech protects expression from improper government restriction."],
["v04","First Amendment","Which definition best matches freedom of religion?",["protection for religious belief and practice and against government establishment","a guarantee that the federal government must financially support every faith","permission to ignore any neutral law by describing an action as a religious practice","a requirement that all citizens belong to a religion selected by a state government"],"Think about both Establishment and Free Exercise.","The First Amendment protects religious exercise and bars government establishment of religion."],
["v05","First Amendment","Which definition best matches Establishment Clause?",["the rule preventing government from establishing or officially favoring religion","the rule requiring government to provide a public building for every religious group","the guarantee that religious organizations may exercise powers belonging to Congress","the procedure allowing states to select one required religion for public schools"],"Government may not create or officially favor a religion.","The Establishment Clause limits government sponsorship or establishment of religion."],
["v06","First Amendment","Which definition best matches Free Exercise Clause?",["protection for practicing religion without improper government interference","authority for government to require participation in an official religious service","permission for religious groups to impose their beliefs through federal criminal law","a guarantee that any action becomes legal when connected to a personal belief"],"Think about exercising or practicing a belief.","The Free Exercise Clause protects religious practice from improper government interference."],
["v07","First Amendment","Which definition best matches freedom of the press?",["the right to publish news and opinions without improper government censorship","the authority of journalists to enter any private location without permission","a guarantee that every published statement is protected even when intentionally false","the power of newspapers to cancel laws passed by Congress or state legislatures"],"Think about publishing news and criticism.","Freedom of the press protects publication from improper government censorship."],
["v08","First Amendment","Which definition best matches freedom of assembly?",["the right to gather peacefully with others for a common purpose","the right to carry weapons into every government building or public meeting","the authority to block all public roads whenever a group supports a political cause","the power to force other citizens to join a protest or political organization"],"Picture people gathering peacefully for a shared cause.","Freedom of assembly protects peaceful gatherings for shared purposes."],
["v09","First Amendment","Which definition best matches right to petition?",["the right to ask government to correct a grievance or change a policy","the power to demand that a court decide every case in a petitioner's favor","the right to refuse taxes until Congress adopts a requested change in policy","the authority to remove an elected official by collecting private signatures"],"Think about formally asking government for change.","The right to petition allows people to ask government to address grievances."],
["v10","Second Amendment","Which definition best matches right to keep and bear arms?",["the Second Amendment protection involving possession and carrying of arms","the constitutional authority to organize a private army that ignores federal and state law","the First Amendment right to bring weapons to every peaceful political demonstration","the guarantee that no government regulation concerning weapons can ever be reviewed"],"This is the central protection named in Amendment II.","The Second Amendment protects the right of the people to keep and bear arms."],
["v11","Fourth Amendment","Which definition best matches unreasonable search and seizure?",["a government search or taking that lacks adequate legal justification","a court-authorized search identifying a specific place and evidence connected to a crime","a temporary inspection that a property owner knowingly and voluntarily permits","a search based on probable cause and a warrant supported by sworn information"],"Think about a search without sufficient legal grounds.","The Fourth Amendment prohibits unreasonable searches and seizures."],
["v12","Fourth Amendment","Which definition best matches search warrant?",["a court order authorizing a particular search based on legal justification","a police request allowing officers to search any person or location they choose","a criminal sentence imposed after a defendant has been convicted at trial","a written accusation automatically proving that a suspect committed an offense"],"A judge issues it before a particular search.","A search warrant is a court order authorizing a particular search."],
["v13","Fourth Amendment","Which definition best matches probable cause?",["reasonable grounds supported by facts for a search, arrest, or warrant","absolute proof that guarantees a person will later be convicted of a crime","a police officer's unsupported guess that something illegal might have happened","permission from a private citizen to search every building in a neighborhood"],"It requires factual grounds—not merely a hunch.","Probable cause means reasonable factual grounds supporting government action."],
["v14","Fifth Amendment","Which definition best matches self-incrimination?",["providing testimony or evidence that could expose oneself to criminal guilt","being required to identify witnesses who will testify for the defense at trial","receiving notice of the exact criminal charges before preparing a defense","questioning a prosecution witness about the reliability of that person's testimony"],"Think about becoming a witness against yourself.","The Fifth Amendment protects against compelled self-incrimination."],
["v15","Fifth Amendment","Which definition best matches double jeopardy?",["being prosecuted twice for the same offense after jeopardy has ended","being charged with two different offenses arising from two separate criminal acts","receiving both imprisonment and a fine following a lawful criminal conviction","asking a higher court to review a legal mistake made during an earlier trial"],"Focus on the same offense being prosecuted a second time.","Double jeopardy generally prevents a second prosecution for the same offense after jeopardy ends."],
["v16","Fifth Amendment","Which definition best matches due process?",["fair legal procedures before government deprives life, liberty, or property","automatic dismissal of every criminal charge challenged by an accused person","authority for officials to punish a person before giving notice or a hearing","a guarantee that every disagreement with government will result in a jury trial"],"Think fair procedure before government takes life, liberty, or property.","Due process requires government to follow fair, established legal procedures."],
["v17","Sixth Amendment","Which definition best matches speedy trial?",["a criminal trial held without unreasonable government delay","a trial completed before the accused person has time to prepare a defense","a court proceeding conducted privately to prevent public observation","a second prosecution started immediately after a defendant is acquitted"],"The key is protection from unreasonable delay.","The Sixth Amendment guarantees a speedy trial."],
["v18","Sixth Amendment","Which definition best matches public trial?",["a criminal trial generally open to observation by the public","a trial in which members of the public vote on the defendant's guilt","a proceeding conducted by Congress instead of an independent court","a hearing in which confidential jury discussions are broadcast publicly"],"Think openness of the courtroom, not a public vote.","The Sixth Amendment generally protects an open, public criminal trial."],
["v19","Sixth Amendment","Which definition best matches impartial jury?",["a group of jurors expected to decide without improper bias","a group chosen entirely by the prosecutor to support the government's case","a panel that reaches its verdict before hearing evidence from either side","a collection of elected officials who determine guilt through a public vote"],"Impartial means fair and unbiased.","An impartial jury evaluates the case without improper bias."],
["v20","Sixth Amendment","Which definition best matches notice of charges?",["the right of an accused person to know the nature and cause of the accusation","a warning that police intend to search any location where evidence might exist","a written statement announcing the punishment before evidence is presented at a criminal trial","a message informing the public that a jury has already reached its verdict"],"A defendant must know what accusation must be defended against.","Notice of charges lets the accused understand the accusation and prepare a defense."],
["v21","Sixth Amendment","Which definition best matches confrontation right?",["the right of an accused person to face and challenge opposing witnesses","the right of a witness to refuse every question asked during a criminal trial","the authority of jurors to question suspects before criminal charges are filed","the power of police to confront anyone during an unlimited warrantless search"],"Think about questioning the witnesses against the accused.","The confrontation right allows the defense to challenge adverse witnesses."],
["v22","Sixth Amendment","Which definition best matches right to counsel?",["the right to assistance from a lawyer in preparing and presenting a defense","the right to have a judge dismiss every charge when an attorney is requested","the power to choose all jurors and control the final verdict in a criminal trial","the authority to require government witnesses to testify for the defense"],"Counsel means legal assistance from an attorney.","The Sixth Amendment protects assistance of counsel for the accused."],
["v23","Eighth Amendment","Which definition best matches excessive bail?",["a bail amount unreasonably high in relation to its lawful purposes","any requirement that an accused person appear in court for a criminal trial","a reasonable condition designed to help ensure a defendant returns to court","a fine imposed after conviction for a serious offense and reviewed by a judge"],"Think about bail set far beyond what is reasonably necessary.","The Eighth Amendment prohibits excessive bail."],
["v24","Eighth Amendment","Which definition best matches excessive fines?",["financial penalties that are grossly disproportionate to the offense","all monetary penalties imposed after a person is lawfully convicted","court costs paid voluntarily as part of a civil settlement agreement","taxes approved by a legislature to finance ordinary public services"],"Think of a financial punishment far out of proportion to the offense.","The Eighth Amendment prohibits excessive fines."],
["v25","Eighth Amendment","Which definition best matches cruel and unusual punishment?",["punishment forbidden because of its unconstitutional severity or character","any lawful sentence that a convicted defendant personally considers unpleasant","every period of imprisonment imposed after conviction for a serious crime","a reasonable fine and sentence authorized after a fair criminal proceeding"],"Think about punishment that crosses constitutional limits.","The Eighth Amendment prohibits cruel and unusual punishments."],
["v26","Federalism","Which definition best matches delegated powers?",["powers granted to the federal government by the Constitution","powers kept by states because the Constitution does not assign them nationally","individual freedoms protected from interference by every private citizen","court procedures required only during state-level criminal prosecutions"],"Delegated means given or assigned.","Delegated powers are granted to the federal government by the Constitution."],
["v27","Federalism","Which definition best matches reserved powers?",["undelegated powers kept by the states or the people","powers granted only to federal courts for deciding constitutional cases","powers transferred permanently from state governments to the president","authority denied to every level of government by the Bill of Rights"],"Think about powers not given to the national government.","Reserved powers are kept by the states or the people."],
["v28","Tenth Amendment","Which definition best matches Tenth Amendment?",["the amendment reserving undelegated powers to the states or the people","the amendment protecting speech, religion, press, assembly, and petition","the amendment requiring probable cause and particular search warrants","the amendment guaranteeing counsel, confrontation, and an impartial jury"],"Connect it to reserved powers and federalism.","The Tenth Amendment reserves undelegated powers to the states or the people."]
];
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function positions(){let p=[0,0,0,0,0,0,0,1,1,1,1,1,1,1,2,2,2,2,2,2,2,3,3,3,3,3,3,3];do{p=shuffle(p)}while(p.some((v,i)=>i>1&&p[i-1]===v&&p[i-2]===v));return p}
const concise={v01:"the list of presidential powers",v02:"duties required of public officials",v03:"the right to vote",v04:"government support for one faith",v05:"freedom to practice religion",v06:"government creation of a church",v07:"the right to petition",v08:"freedom of the press",v09:"freedom of assembly",v10:"the right to petition",v11:"a valid warrant search",v12:"a police officer's request",v13:"proof beyond all doubt",v14:"notice of charges",v15:"an appeal after conviction",v16:"immediate punishment",v17:"a private trial",v18:"a jury trial",v19:"a grand jury",v20:"a search warrant",v21:"the right to counsel",v22:"an impartial jury",v23:"a criminal fine",v24:"a tax increase",v25:"an unpopular sentence",v26:"powers kept by states",v27:"powers granted to Congress",v28:"the First Amendment"};
const ordered=shuffle(raw),pos=positions();
window.BLOCK_QUESTIONS=ordered.map((r,n)=>{const correct=r[3][0],wrong=r[3].slice(1);wrong[0]=concise[r[0]];const answer=pos[n],choices=shuffle(wrong);choices.splice(answer,0,correct);return{id:r[0],cs:"CS 8",topic:r[1],prompt:r[2],choices,answer,source:"",where:"",hint:r[4],explanation:r[5]}});
})();
