const SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";const META={title:'CS 14–15 Rights Responsibilities and Civil Rights Intro',assignmentKey:'gov-cs14-15-intro-2026-v1'};
const URL={rights:'https://constitutioncenter.org/the-constitution/articles/article-i/clauses/750',inc:'https://constitutioncenter.org/the-constitution/articles/amendment-xiv/clauses/701',civil:'https://www.archives.gov/research/african-americans/civil-rights'};const A=(id,n,section,prompt,hint,keys,link,min)=>({id,n,section,prompt,hint,keys,link,min});
const QS=[
A('q1',1,'CS 14 • Rights','What are rights?','Explain rights as protected claims against undue government interference.',[['protect'],['government'],['freedom','liberty','claim']],URL.rights,2),
A('q2',2,'CS 14 • Participation','Name four rights that support political participation.','Choose from speech, press, assembly, petition, suffrage, and holding public office.',[['speech'],['press'],['assembl'],['petition'],['vote','suffrage'],['office']],URL.rights,4),
A('q3',3,'CS 14 • Incorporation','What is the doctrine of incorporation?','Find the Fourteenth Amendment due process discussion. It applies most Bill of Rights protections to states and localities.',[['bill of rights','rights'],['state','local'],['fourteenth','14th','due process','incorpor']],URL.inc,3),
A('q4',4,'CS 14 • General Responsibilities','Name three general responsibilities of citizenship.','Use the Ohio list: respect rule of law, pay taxes/fees, accept responsibility for actions.',[['law'],['tax','fee'],['responsibility','actions','account']],URL.rights,3),
A('q5',5,'CS 14 • Speech','What responsibility is connected to free speech?','The state standard pairs speech with civil discourse—respectful discussion.',[['civil'],['discourse','respect','discussion']],URL.rights),
A('q6',6,'CS 14 • Arms','What responsibility is connected to the right to bear arms?','The state standard identifies firearms training.',[['training','safety'],['firearm','gun','arms']],URL.rights),
A('q7',7,'CS 14 • Jury Trial','What responsibility supports the right to a jury trial?','Courts need citizens to serve as jurors when called.',[['serve','service'],['jury','juror']],URL.rights),
A('q8',8,'CS 14 • Voting','What responsibilities support the right to vote?','Name both registering and becoming informed about public issues.',[['register'],['informed','learn','research'],['vote','issue','candidate']],URL.rights,2),
A('q9',9,'CS 14 • Service','Give two ways citizens can serve the nation or state.','Choose military service, community service, or serving in public office.',[['military','community','public office'],['service','serve']],URL.rights),
A('q10',10,'CS 14 • Limits','Why are rights relative rather than absolute?','Explain that exercising rights must respect others’ rights and the common good.',[['other','others'],['right'],['common good','public safety','community','balance']],URL.rights,2),
A('q11',11,'CS 15 • Civil Rights','What tension exists between majority rule and minority rights?','A majority may make decisions but may not deny constitutional rights to a minority.',[['majority'],['minority'],['right'],['protect','deny','limit']],URL.civil,3),
A('q12',12,'CS 15 • Amendments','Give two amendment examples that expanded participation.','Use women’s suffrage and elimination of poll taxes: 19th and 24th Amendments.',[['19','nineteenth','women'],['24','twenty fourth','poll tax']],URL.civil,2),
A('q13',13,'CS 15 • Executive','How did the executive branch help integrate schools?','Use Little Rock or Alabama: federal troops/enforcement protected integration.',[['troop','federal','executive','president'],['integrat','school','little rock','alabama']],URL.civil,2),
A('q14',14,'CS 15 • Legislative','How did Congress extend civil rights?','Identify civil rights acts or voting rights acts.',[['civil rights act','voting rights act','law','legislation'],['congress','legislative']],URL.civil,2),
A('q15',15,'CS 15 • Judicial','How did the Supreme Court extend rights through incorporation?','Explain that it used Fourteenth Amendment due process to apply most Bill of Rights protections to states.',[['supreme court','court'],['fourteenth','due process'],['bill of rights'],['state']],URL.inc,3),
A('q16',16,'CS 15 • Analysis','Why has extending civil rights often required action by several branches?','Connect laws, executive enforcement, and court interpretation to overcoming denial of rights.',[['legislative','congress','law'],['executive','president','enforce'],['judicial','court','interpret']],URL.civil,2)
];
const state={accepted:{}},LOCAL=META.assignmentKey+'::local-v1';const norm=s=>String(s||'').toLowerCase().replace(/[’']/g,'').replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function check(q,v){const t=norm(v),hits=q.keys.filter(g=>g.some(k=>t.includes(norm(k)))).length,need=q.min||q.keys.length;return t.length>=2&&hits>=need}
function collect(){const answers={};QS.forEach(q=>answers[q.id]=document.getElementById('answer-'+q.id)?.value||'');return{assignmentKey:META.assignmentKey,assignmentTitle:META.title,name:studentName.value.trim(),period:period.value,email:email.value.trim().toLowerCase(),answers,accepted:state.accepted}}
function saveLocal(){localStorage.setItem(LOCAL,JSON.stringify(collect()))}function progress(){progressText.textContent=`${QS.filter(q=>state.accepted[q.id]).length} of ${QS.length} responses accepted`}
function apply(d){if(!d)return;studentName.value=d.name||'';period.value=d.period||'';email.value=d.email||'';QS.forEach(q=>{const ta=document.getElementById('answer-'+q.id);ta.value=d.answers?.[q.id]||'';state.accepted[q.id]=!!d.accepted?.[q.id];ta.closest('.q').classList.toggle('accepted',state.accepted[q.id]);document.getElementById('feedback-'+q.id).textContent=state.accepted[q.id]?'Accepted ✓':''});progress()}
function render(){let section='';assignment.innerHTML=QS.map(q=>{const h=q.section!==section?`<h2 class="section-title">${esc(section=q.section)}</h2>`:'';return h+`<article class="q"><div class="qtop"><div class="num">${q.n}</div><div class="prompt">${esc(q.prompt)}</div></div><div class="hint"><b>Where to look:</b> ${esc(q.hint)}</div><a class="source-link" href="${q.link}" target="_blank" rel="noopener">Find it here: official source ↗</a><div class="response-row"><textarea id="answer-${q.id}" placeholder="Type a short answer in your own words…"></textarea><button type="button" data-id="${q.id}">Check Answer</button></div><div class="feedback" id="feedback-${q.id}"></div></article>`}).join('');document.querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>{const q=QS.find(x=>x.id===b.dataset.id),card=b.closest('.q'),ok=check(q,document.getElementById('answer-'+q.id).value);state.accepted[q.id]=ok;card.classList.toggle('accepted',ok);card.classList.toggle('retry',!ok);document.getElementById('feedback-'+q.id).textContent=ok?'Accepted ✓':'Use the “Where to look” direction and add the missing main idea.';saveLocal();progress()});document.querySelectorAll('textarea').forEach(t=>t.oninput=()=>{state.accepted[t.id.slice(7)]=false;t.closest('.q').classList.remove('accepted','retry');saveLocal();progress()});try{apply(JSON.parse(localStorage.getItem(LOCAL)))}catch{}progress()}
async function cloud(status){const d=collect();if(!d.name||!d.period||!d.email){saveStatus.textContent='Enter name, period, and school email first.';return}saveLocal();await fetch(SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,...d,score:QS.filter(q=>state.accepted[q.id]).length,total:QS.length})});saveStatus.textContent=status==='submitted'?'Submission sent.':'Progress save sent.'}
function retrieve(){const mail=email.value.trim().toLowerCase();if(!mail){saveStatus.textContent='Enter the same school email used when saving.';return}const cb='load_'+Date.now();window[cb]=r=>{try{if(r?.found){apply(r.payload);saveLocal();saveStatus.textContent='Saved work retrieved.'}else saveStatus.textContent='No saved work was found.'}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(META.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+cb;document.body.appendChild(s);saveStatus.textContent='Looking for saved work…'}
saveBtn.onclick=()=>cloud('in_progress');retrieveBtn.onclick=retrieve;finishBtn.onclick=async()=>{await cloud('submitted');const d=collect(),score=QS.filter(q=>state.accepted[q.id]).length;finalResult.innerHTML=`<div class="receipt"><h2>Submission Complete</h2><p><b>${esc(d.name)}</b> • Period ${esc(d.period)}</p><p><b>${score}/${QS.length} accepted</b></p></div>`};render();
