const GOV_SCRIPT_URL="https://script.google.com/macros/s/AKfycbyAkahbkT3Tn7wVxAap3EqF1uhnB2iJF9hm6pnuUueHkBibHUgZg2R8ZVEHE-Gky6y7/exec";
function launchMasteryGame(config){
 const app=document.getElementById('app'),key=config.assignmentKey+'::v1';
 const S={started:false,index:0,attempts:0,items:[],start:null,end:null,timer:null,name:'',period:'',email:'',events:[]};
 const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
 const shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
 const elapsed=()=>{if(!S.start)return'00:00';const sec=Math.floor(((S.end||new Date())-S.start)/1000);return`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`};
 function fresh(){S.items=shuffle(config.questions).map(q=>({...q,choices:shuffle(q.choices),missed:false,mastered:false}));S.index=0;S.attempts=0;S.start=new Date();S.end=null;S.events=[]}
 function identity(){return{name:S.name,period:S.period,email:S.email}}
 function save(){localStorage.setItem(key,JSON.stringify({...identity(),started:S.started,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events}))}
 function restore(){try{const d=JSON.parse(localStorage.getItem(key));if(!d)return false;Object.assign(S,d,{start:d.start?new Date(d.start):null});return true}catch{return false}}
 function log(type,extra={}){S.events.push({type,at:new Date().toISOString(),index:S.index,...extra});save()}
 function post(status){if(!GOV_SCRIPT_URL)return;const first=S.items.filter(q=>q.mastered&&!q.missed).length,pct=Math.round(first/S.items.length*100),gameState={started:true,index:S.index,attempts:S.attempts,items:S.items,start:S.start?.toISOString(),events:S.events};fetch(GOV_SCRIPT_URL,{method:'POST',mode:'no-cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({action:'save',status,assignmentKey:config.assignmentKey,assignmentTitle:config.title,...identity(),score:first,total:S.items.length,percent:pct,attempts:S.attempts,startedAt:S.start?.toISOString(),completedAt:S.end?.toISOString()||'',elapsed:elapsed(),events:S.events,gameState})}).catch(()=>{})}
 function launch(){const n=document.getElementById('name').value.trim(),p=document.getElementById('period').value,e=document.getElementById('email').value.trim().toLowerCase();if(!n||!p||!e){document.getElementById('status').textContent='Enter your name, period, and school email.';return}S.name=n;S.period=p;S.email=e;S.started=true;fresh();log('start');post('in_progress');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function resume(){const mail=document.getElementById('email').value.trim().toLowerCase();if(!mail){document.getElementById('status').textContent='Enter the same school email used when saving.';return}if(restore()&&S.started&&S.email===mail){render();startTimer();return}const status=document.getElementById('status');status.textContent='Looking for saved work…';const cb='loadGame_'+Date.now();window[cb]=r=>{try{const p=r&&r.found&&r.payload;if(!p||!p.gameState){status.textContent='No saved run was found for that email.';return}Object.assign(S,p.gameState,{name:p.name||'',period:p.period||'',email:p.email||mail,start:new Date(p.gameState.start),started:true});save();render();startTimer()}finally{delete window[cb];document.getElementById(cb)?.remove()}};const s=document.createElement('script');s.id=cb;s.src=GOV_SCRIPT_URL+'?action=load&assignmentKey='+encodeURIComponent(config.assignmentKey)+'&email='+encodeURIComponent(mail)+'&callback='+encodeURIComponent(cb)+'&_='+Date.now();s.onerror=()=>status.textContent='Cloud retrieval was blocked. No local run was found.';document.body.appendChild(s)}
 function startTimer(){if(S.timer)clearInterval(S.timer);S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function choose(btn,value){const q=S.items[S.index];if(q.mastered)return;S.attempts++;document.querySelectorAll('.choice').forEach(b=>b.classList.remove('wrong'));if(value!==q.answer){q.missed=true;btn.classList.add('wrong');document.getElementById('feedback').className='feedback show hint';document.getElementById('feedback').innerHTML=`<b>Hint</b>${esc(q.hint)}`;log('incorrect',{area:q.area});return}q.mastered=true;btn.classList.add('correct');document.querySelectorAll('.choice').forEach(b=>b.disabled=true);document.getElementById('feedback').className='feedback show good';document.getElementById('feedback').innerHTML=`<b>Correct</b>${esc(q.explain)}`;log('correct',{area:q.area,firstTry:!q.missed});post('in_progress');setTimeout(()=>{S.index++;save();render()},config.linger||3500)}
 function restart(){if(S.timer)clearInterval(S.timer);fresh();log('restart');render();S.timer=setInterval(()=>{const x=document.getElementById('clock');if(x)x.textContent=elapsed()},1000)}
 function finish(){if(S.timer)clearInterval(S.timer);S.end=new Date();const first=S.items.filter(q=>!q.missed).length,perfect=first===S.items.length,pct=Math.round(first/S.items.length*100);log('finish',{perfect});post(perfect?'submitted':'needs_retry');localStorage.setItem(key,JSON.stringify({...S,end:S.end.toISOString(),start:S.start.toISOString()}));app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="result"><div class="kicker">${perfect?'Mastery Ticket Earned':'Review Complete • Ticket Locked'}</div><h1>${esc(config.title)}</h1><p class="sub">${perfect?'Perfect first-try mastery. Show this ticket to your teacher.':'You corrected every item, but a perfect first-try run is required. Review the missed areas and restart.'}</p><div class="stats"><span class="stat">Accuracy: ${pct}%</span><span class="stat">First try: ${first}/${S.items.length}</span><span class="stat">Attempts: ${S.attempts}</span><span class="stat">Time: ${elapsed()}</span></div><div class="ticket ${perfect?'':'locked'}"><h2>${perfect?'Completion Ticket':'Ticket Locked'}</h2><p><b>${esc(S.name)}</b> • Period ${esc(S.period)}<br>${esc(config.title)}<br>${new Date().toLocaleString()}<br>${perfect?'Status: 100% PERFECT RUN':'Restart required'}</p></div><button class="btn" id="restart">Restart Full Game</button></section>`;document.getElementById('restart').onclick=restart}
 function render(){if(!S.started){app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="hero"><div class="kicker">Legend Mastery Series • American Government</div><h1>${esc(config.title)}</h1><p class="sub">${esc(config.subtitle)}</p><div class="pills"><span class="pill">${config.questions.length} questions</span><span class="pill">Hint after a miss</span><span class="pill">Auto-check</span><span class="pill">100% run required</span></div></section><section class="panel"><div class="identity"><label>Name<input id="name" autocomplete="name"></label><label>Period<select id="period"><option value="">Choose…</option>${[1,2,3,4,5,6,7,8].map(x=>`<option>${x}</option>`).join('')}</select></label><label>School email<input id="email" type="email" autocomplete="email"></label></div><button class="btn" id="start">Start Assignment</button> <button class="btn secondary" id="resume">Retrieve Saved Run</button><div class="status" id="status"></div></section>`;document.getElementById('start').onclick=launch;document.getElementById('resume').onclick=resume;return}if(S.index>=S.items.length){finish();return}const q=S.items[S.index],first=S.items.slice(0,S.index).filter(x=>!x.missed).length,acc=S.index?Math.round(first/S.index*100):100;app.innerHTML=`<a class="back" href="../../">← Back to Government Hub</a><section class="question"><div class="topline"><div><div class="area">${esc(q.area)}</div><b>Question ${S.index+1} of ${S.items.length}</b></div><div class="stats"><span class="stat">Accuracy ${acc}%</span><span class="stat" id="clock">${elapsed()}</span></div></div><div class="progress"><div style="width:${S.index/S.items.length*100}%"></div></div><div class="stem">${esc(q.stem)}</div><div class="choices">${q.choices.map(c=>`<button class="choice" data-value="${esc(c)}">${esc(c)}</button>`).join('')}</div><div id="feedback" class="feedback"></div></section>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,b.dataset.value))}
 render();window.addEventListener('beforeunload',save);document.addEventListener('visibilitychange',()=>{if(S.started)log(document.hidden?'tab_leave':'tab_return')});document.addEventListener('copy',()=>S.started&&log('copy'));document.addEventListener('paste',()=>S.started&&log('paste'));
}
const Q=(area,stem,answer,wrong,hint,explain)=>({area,stem,answer,choices:[answer,...wrong],hint,explain});
const questions=[
Q('CS 12 • Law','Which statement best defines a law?','a binding rule recognized and enforced by government',['a suggestion issued by a private group','a news report about politics','an informal friendship among officials'],'Focus on enforceability.','Laws are binding government rules.'),
Q('CS 12 • Public policy','Which example is public policy?','a government program and procedures created to address water quality',['a family choosing a vacation','a private club choosing uniforms','a reporter writing a personal diary'],'Look for institutional government action.','Public policy is government action undertaken to carry out public functions.'),
Q('CS 12 • Legislative','Congress debates and passes a national education law. Which branch responsibility is illustrated?','legislative branch makes laws',['executive branch interprets laws','judicial branch imposes taxes','executive branch declares war'],'Congress is the lawmaking institution.','Making laws is a legislative responsibility.'),
Q('CS 12 • Legislative','Which branch has constitutional authority to declare war?','legislative branch',['executive branch','judicial branch','state judiciary'],'Think Congress.','CS 12 identifies declaring war as a legislative power.'),
Q('CS 12 • Legislative','Congress increases an excise tax to fund a program. Which responsibility is illustrated?','legislative power to impose taxes',['judicial power to hear appeals','executive power to issue pardons','judicial power to receive ambassadors'],'Taxes are imposed through legislation.','Taxation is one of Congress’s listed responsibilities.'),
Q('CS 12 • Executive','A federal agency carries out requirements of a new law. Which branch function is illustrated?','executive branch enforces laws',['legislative branch hears appeals','judicial branch declares war','legislative branch receives ambassadors'],'Agencies administer laws.','The executive implements and enforces legislation.'),
Q('CS 12 • Executive','The president directs executive agencies through a formal written directive. What is this?','executive order',['judicial opinion','constitutional amendment','veto override'],'It directs executive operations.','Executive orders are presidential directives within the executive branch.'),
Q('CS 12 • Executive','The president names a diplomat to represent the United States abroad. Which responsibility is involved?','appointing an ambassador',['hearing an appeal','imposing a tax','declaring a law unconstitutional'],'Think diplomacy.','The executive appoints and receives ambassadors.'),
Q('CS 12 • Judicial','A federal court explains the meaning of a disputed statute. Which branch function is illustrated?','judicial branch interprets law',['executive branch makes law','legislative branch hears appeals','executive branch imposes taxes'],'Courts resolve legal meaning.','Interpreting laws is a judicial responsibility.'),
Q('CS 12 • Judicial','The Supreme Court is the first court to hear a dispute between two states. What type of authority is this?','original jurisdiction',['appellate jurisdiction','executive privilege','legislative oversight'],'The case begins there.','Original jurisdiction means authority to hear a case first.'),
Q('CS 12 • Judicial','A federal appeals court reviews a lower court’s decision. What type of authority is this?','appellate jurisdiction',['original jurisdiction','executive order','legislative veto'],'An appeal asks a higher court to review.','Appellate jurisdiction is authority to review lower-court decisions.'),
Q('CS 12 • Comparison','Which comparison is correct?','Congress makes policy through laws; the executive implements it; courts interpret it.',['Courts make taxes; Congress hears appeals; the president interprets all laws.','The president declares war; courts appoint ambassadors; Congress grants pardons.','All three branches perform identical functions.'],'Follow make → enforce → interpret.','The three branches contribute distinct but connected functions.'),
Q('CS 13 • Veto','The president rejects a bill passed by Congress. Which check is used?','executive veto',['judicial review','Senate confirmation','impeachment'],'The bill is returned unsigned.','A veto is an executive check on legislation.'),
Q('CS 13 • Override','Congress passes a vetoed bill with the required supermajorities. Which check is used?','legislative veto override',['executive pardon','judicial nomination','original jurisdiction'],'Congress can overcome a veto.','An override checks the president’s veto power.'),
Q('CS 13 • Impeachment','The House formally accuses a federal civil officer of misconduct. What action is this?','impeachment',['pardon','confirmation','judicial review'],'Formal accusation occurs in the House.','Impeachment is the House’s formal charge.'),
Q('CS 13 • Removal','After a House impeachment, which body conducts the trial that can lead to removal?','Senate',['Supreme Court','Cabinet','Electoral College'],'The other chamber tries the case.','The Senate tries impeachments and may convict and remove.'),
Q('CS 13 • Appointments','The president nominates a cabinet secretary. Which branch checks this appointment?','Senate through confirmation',['Supreme Court through appeal','House through a veto','states through ratification'],'Think advice and consent.','Senate confirmation checks presidential appointments.'),
Q('CS 13 • Treaties','The president negotiates a treaty. What check occurs before ratification?','Senate approval',['House impeachment','Supreme Court nomination','presidential pardon'],'Treaties require Senate consent.','The Senate checks executive treaty-making power.'),
Q('CS 13 • Judges','Who nominates federal judges?','president',['House of Representatives','Supreme Court','state governors collectively'],'This is an executive check involving the judiciary.','The president nominates federal judges; the Senate confirms.'),
Q('CS 13 • Judges','Why can the president not remove a federal judge merely for an unfavorable decision?','judicial independence prevents presidential removal at will',['the judge controls the military','Congress cannot regulate courts','the judge was elected nationally'],'Life tenure protects courts from executive pressure.','Federal judges are not subject to removal by the president.'),
Q('CS 13 • Pardons','The president forgives a person’s federal criminal offense. Which power is used?','pardon',['reprieve','veto override','impeachment'],'Forgiveness rather than delay.','A pardon is executive clemency for a federal offense.'),
Q('CS 13 • Reprieves','The president temporarily delays a federal sentence. Which power is used?','reprieve',['pardon','judicial review','confirmation'],'Temporary delay is the clue.','A reprieve postpones punishment.'),
Q('CS 13 • Judicial review','A court declares a federal statute unconstitutional. Which check is illustrated?','judicial check on the legislative branch',['executive check on the judiciary','legislative check on the executive','state check on Congress'],'A court is reviewing a law.','Judicial review allows courts to invalidate unconstitutional legislation.'),
Q('CS 13 • Judicial review','A court declares an executive order unconstitutional. Which check is illustrated?','judicial check on the executive branch',['legislative override','executive pardon','Senate treaty approval'],'A court is reviewing executive action.','Judicial review also checks unconstitutional executive acts.'),
Q('CS 13 • Amendments','Congress disagrees with a constitutional interpretation and initiates a formal change. What may Congress do?','propose a constitutional amendment',['remove judges by presidential order','issue a judicial pardon','cancel state elections'],'A formal change follows Article V.','Congress may propose amendments, which then require state ratification.'),
Q('CS 13 • Interaction','The president proposes a policy, Congress passes funding, and courts resolve a later dispute. What does this show?','dynamic interaction among all three branches',['complete separation with no interaction','judicial control of elections','state nullification'],'All three branches affect the same issue.','Public policy commonly develops through branch cooperation and conflict.'),
Q('CS 13 • Interest groups','An organization proposes bill language and asks legislators to support it. Which influence is shown?','interest group involvement',['appellate jurisdiction','presidential succession','judicial removal'],'An organized group is advocating policy.','Interest groups try to shape legislation.'),
Q('CS 13 • Interest groups','An advocacy organization files an amicus brief in a court case. What is it trying to do?','influence judicial consideration with arguments or information',['veto a law directly','confirm a judge','declare war'],'The group is not a party but supplies a brief.','Amicus briefs are one channel for interest-group influence on courts.'),
Q('CS 13 • Party control','The president and congressional majority belong to opposing parties. What condition may increase conflict?','divided government',['original jurisdiction','unified judiciary','electoral succession'],'Party control is split.','Divided government can make cooperation more difficult.'),
Q('CS 13 • Party control','The president and congressional majorities share a party and coordinate on a bill. What may this produce?','greater branch cooperation on a shared agenda',['automatic judicial approval','elimination of checks and balances','removal of all opposition rights'],'Shared party goals can affect interaction.','Unified party control may make coordination easier, though checks remain.'),
Q('CS 13 • Public interest','A highly visible issue produces calls, protests, and extensive constituent pressure. What factor is influencing officials?','amount of public interest',['original jurisdiction','presidential disability','naturalization'],'The public is paying close attention.','Public interest can shape how branches prioritize issues.'),
Q('CS 13 • Media','Continuous news coverage increases attention to an agency rule. What influence is shown?','media coverage and commentary',['veto override','judicial nomination','treaty ratification'],'News attention changes the political environment.','Media coverage can amplify public pressure and affect branch responses.'),
Q('CS 13 • Informal relations','Legislators and executive officials resolve details through personal negotiations. What factor is shown?','informal relationships among branch members',['formal amendment','original jurisdiction','impeachment conviction'],'Not every interaction is formally required.','Informal working relationships can support policy cooperation.'),
Q('CS 13 • Cause and effect','Which relationship is correct?','A presidential veto can cause Congress to revise a bill or attempt an override.',['A judicial nomination automatically removes Congress.','A pardon causes the Senate to declare war.','An appeal allows the president to impose taxes.'],'Match a check with a realistic response.','Checks create responses and negotiation among branches.'),
Q('CS 12–13 • Synthesis','Which statement best summarizes CS 12–13?','Branches have distinct policy roles but continually cooperate check one another and respond to political influences.',['Each branch acts alone without affecting the others.','Only courts create public policy.','Interest groups formally replace elected branches.'],'Combine separate powers with dynamic interaction.','Government policy emerges from branch responsibilities, checks, cooperation, and political context.'),
Q('CS 12–13 • Application','What is the best approach to a branch-interaction scenario?','identify the actor action target branch and resulting check or policy effect',['choose the longest amendment number','assume every action is judicial review','ignore which branch acts first'],'Track who does what to whom.','Identifying actors and effects reveals the relevant power or check.')
];
launchMasteryGame({title:'CS 12–13 Branches and Public Policy Comprehensive Review',subtitle:'Apply branch powers, checks and balances, and political influences to short public-policy scenarios.',assignmentKey:'gov-cs12-13-review-2026-v1',questions,linger:3800});
